### ISSUE TITLE
Wrong temperature (-3°) shown

### ISSUE THREAD

**Issue by ryanchucks** [damianxd/homebridge-vera#101]
Previously, I had the issue of not being able to turn on devices (but able to turn off), and sensors not showing up. I installed directly from GitHub URL (as described in #100) and that resolved the issue.

But a new issue cropped up after that, which is my temperature sensors now read -3°. This shouldn't be a Fahrenheit to Celsius conversion issue; before this, the readings were correct. Removing/re-adding the bridge in Home app and deleting persist and accessories folders didn't help.

Any ideas what could be the issue? Thanks.

**Comment by roflcoopter** [comment]
I am also having this same issue. Everything else is working fine.

**Comment by drewcovi** [comment]
Can either or both of you confirm that you've installed directly from master (using the GitHub URL?)

**Comment by roflcoopter** [comment]
I installed using `sudo npm install -g --unsafe-perm damianxd/homebridge-vera`

Correct?

**Comment by drewcovi** [comment]
I believe that should work, but I'd use the URL to be certain. I'm not totally sure if NPM checks if there's a match or just pulls from github

**Comment by roflcoopter** [comment]
So it should be 

`sudo npm install -g --unsafe-perm https://github.com/damianxd/homebridge-vera`

I'll try it out tonight and report back

**Comment by roflcoopter** [comment]
Installing the method above still gives wrong temperature. Shows -6C when its actually 21C

**Comment by ryanchucks** [comment]
Same here. Installing from GitHub URL doesn't solved it.

I did remember it used to work previously, at the time when I had the "can turn off lights, but cannot turn on" issue.

So perhaps something has changed (new commits, etc.) between the versions then and now that caused this issue.

**Comment by ryanchucks** [comment]
Just guessing: could it be this [commit](https://github.com/damianxd/homebridge-vera/commit/b4b6a54cb22bc1a1f49cbbe547ae9e7e8de28795)?

@roflcoopter 's 21C showing -6C could be because (21-32)/1.8=-6.11111 and
my 27C showing -3C could be (27-32)/1.8=-2.777777.

Perhaps the Fahrenheit to Celsius conversion is taking place when there's no need to?

**Comment by drewcovi** [comment]
Hmmm thought that was a HomeKit setting. I'll check.

**Comment by drewcovi** [comment]
Spot on. I think I've figured it out. When I get the little one down ill patch this @roflcoopter

**Comment by neptunix** [comment]
As fas as I can see , you are calling 'tempsense.js' newDevice() without passing a temp parameter, so the temperature is always assumed Fahrenheit 

```
case 17: // Temp sensor
                          if(config.includesensor)
                          {
                              var Tempsense       = require("./types/tempsense.js")(HAPnode,config,module);
                              HAPnode.debug('------ Temp sensor Added: %s', device.name + ' ID:' +device.id);
                              accessories.push(Tempsense.newDevice(device));
                          }
                      break;
```

```
 module.newDevice = function(device, tempDisplayUnit)
```

**Comment by drewcovi** [comment]
Correct

**Comment by drewcovi** [comment]
Should be resolved now with https://github.com/damianxd/homebridge-vera/pull/113
