### ISSUE TITLE
Fibaro switch 2  is not controlling... 

### ISSUE THREAD

**Issue by kpacota** [damianxd/homebridge-vera#103]
Hallo
I had installed Homebridge following to instructions 
Vera now is in my Homelink app, and i can see Fibaro switch 2 in device list, BUT...
It can read the state of the device properly (it is on of off), but I can't control if with HomeKit app (controlling with Vera app is just fine).
Please help!))

**Comment by machinen** [comment]
What I have noticed is that a couple of classes is not the same as when installed via sudo npm install -g homebridge-vera (I don't know if they are different sources and need to be synced). I have copied the content of light.js file from GitHub rep to RaspberryPi, then lights started working.

**Comment by drewcovi** [comment]
@machinen please install using the github URL to get master. I'm unable to tag and publish releases to NPM. I'll touch base with @damianxd to see if there's a way I can become a contributor (or rather publisher) there as well.

**Comment by kpacota** [comment]
I`m newbie in codeing((
Can you please describe what i exactly must do?)) 
Thx!

**Comment by kpacota** [comment]
Also i had this

>

>  pi@raspberrypi:~ $ DEBUG=* node VeraLink.js
> module.js:471
>     throw err;
>     ^
> 
> Error: Cannot find module '/home/pi/VeraLink.js'
>     at Function.Module._resolveFilename (module.js:469:15)
>     at Function.Module._load (module.js:417:25)
>     at Module.runMain (module.js:604:10)
>     at run (bootstrap_node.js:394:7)
>     at startup (bootstrap_node.js:149:9)
>     at bootstrap_node.js:509:3
> pi@raspberrypi:~ $
