### ISSUE TITLE
Scenes don't work in Apples Home app

### ISSUE THREAD

**Issue by pearldrum** [damianxd/homebridge-vera#107]
Hi,

If I make a scene in the Home app on my iPhone, i.e. Good Night, to turn all my lamps off, only one lamp turn off and the rest stays on.
No matter what scenes I create it doesn't work if it's more than one lamp involved.

Anyone else having trouble with this?

/Oliver

**Comment by drewcovi** [comment]
@pearldrum can you install from master (use the github URL) and follow up? Npm is really out of date.

**Comment by pearldrum** [comment]
@drewcovi That sorted it. Thanks!
