### ISSUE TITLE
On/off switch problem. Always sends off command

### ISSUE THREAD

**Issue by roflcoopter** [damianxd/homebridge-vera#108]
Edit: Apparently i didnt go through the closed Issues properly. 
Installing using `sudo npm install -g --unsafe-perm damianxd/homebridge-vera` as instructed in [issue#100](https://github.com/damianxd/homebridge-vera/issues/100) solved it

Hi,

Edit: Solved the dimming problem by doing a fresh install of Hombridge and homebridge-vera.
Im still having issues with on/off switches, it seems that homebridge-vera always sends an off command, never on. If the switch is on and tell Siri to turn it on, it turns off. Telling Siri again to turn on does nothing, but in my Vera interface i can see that the device recieved an off command.

Original question that is now solved:
I am having trouble with dimming a light via Siri, the lamps always go to 100%. Dimmable switches work fine but not dimmable lights.

I read issue#99 that is also related to dimming but it didnt solve anything for me.

I installed using **npm install https://github.com/damianxd/homebridge-vera.git**
Should i install it in some other way?

Thanks in advance

**Comment by drewcovi** [comment]
👍
