### ISSUE TITLE
Light Switches not Working

### ISSUE THREAD

**Issue by HA-Enthusiast** [damianxd/homebridge-vera#110]
This is a pretty odd one. I have GE Smart Light Switches installed in my home. Kitchen Lights, Main Deck Light, Fireplace Lights, and Porch Lights. 

They are all the same brand and all installed in the exact same way on my VeraEdge; however, the Home app only lets me control two of them (Fireplace and Porch). The other two I can only turn off, but not on. In the settings of the devices that do not work properly, it does not give me the option to change the device between a switch and a light like the other two that work do... I hope that makes sense. 

Does anyone have this issue?

**Comment by drewcovi** [comment]
Check the category / subcategory in the advanced tab for each device on the Vera. Are they all the same?

**Comment by HA-Enthusiast** [comment]
Made sure all the slight switches that weren't working matched the category and subcategory of the ones that were working. The lights that weren't working were labeled as subcategory 0 and the ones that were working were labeled 3. Changed them all, restarted homebridge, nada. 

Should I have restarted diefferently? Any other suggestions?

**Comment by drewcovi** [comment]
So small pro-tip on changing subcategories: Vera is a mess. I'd change it a few times, save button from the device screen and even reload the Lua Engine under ZWave settings. Double check changing the subcategory sticks.

**Comment by HA-Enthusiast** [comment]
I've reloaded several times. All the changes I've made have stuck. 

Do you know that this is actually the problem? In other words, could it be something to do with Homebridge?

**Comment by drewcovi** [comment]
Hmmm it sounds like everything is fine and I wouldn't expect it to matter too much when it comes to the subcategories. Rather the category which is responsible for picking the dimmer or switch device type from this plugin. If you refresh your browser and all of your dimmers are in category 2 in UI 7 then you should be good to go. 

http://wiki.micasaverde.com/index.php/Luup_Device_Categories

**Comment by drewcovi** [comment]
Of course you would still need to restart homebridge to ensure you're not working with the cached device types. That mapping mentioned above only happens on homebridge startup

**Comment by drewcovi** [comment]
But no. It's not homebridge if things are showing up as the wrong type. It's really as simple as matching category and in some cases subcategory.

**Comment by HA-Enthusiast** [comment]
Alright.

The ones that work are labeled category: 3; subcategory: 3

The ones that still do not work are labeled category: 3; subcategory: 3

Should I try changing the numbers to all of them?

**Comment by drewcovi** [comment]
I think you might have a really old version of homebridge-Vera. 9/10 times I tell folks on these issues to download direct from the GitHub URL instead of just NPM installing homebridge-Vera. 

I'm still working to get NPM access so I can publish the latest changes. 

Can you install homebridge-Vera from the URL instead and let me know if you're good?

**Comment by HA-Enthusiast** [comment]
First of all, I really really appreciate your timely responses and helping me figure out this problem. Thank you.

Secondly, how do I install it from the URL onto my RPi? Just a heads up: I'm not SSH'ing into it. I installed it via the Raspbian UI and have the console running constantly (mostly because I can't figure out how to load homebridge on bootup... I tired and it took me weeks to fix it).

**Comment by drewcovi** [comment]
I didn't even know that was possible. You'll have to jump into the terminal on Raspbian UI and just type '''npm install -g [URL]''' to install any GitHubd npm package.

**Comment by HA-Enthusiast** [comment]
So that I don't screw it up, would you mind pasting the URL here. Lol

**Comment by drewcovi** [comment]
https://github.com/damianxd/homebridge-vera

**Comment by HA-Enthusiast** [comment]
It works! Thank you! Now, my only complaint is that Homebridge is no longer ignoring all the devices I outlined in my confit.json file. Any suggestions there?

**Comment by HA-Enthusiast** [comment]
Config.json*

**Comment by drewcovi** [comment]
definitely should be... id just check the format and open another ticket :)

**Comment by drewcovi** [comment]
and congrats! glad its working.
