### ISSUE TITLE
Mapping device types? 

### ISSUE THREAD

**Issue by djrobx** [damianxd/homebridge-vera#112]
For the most part this works wonderfully, but I have one crazy issue:

I have something like 40 Z-wave switches.   Almost everything is mapped to a "light" device type in HomeKit.   Some of them aren't really lights, like my pool filter pump, and my fireplace.    Some fans are also on appliance modules. 

The problem: Siri sometimes doesn't hear me correctly when I say 'turn the livingroom light on".   Sometimes she just hears "turn the light on".   And then all holy automation hell breaks loose.  My fireplace turns on, my pool pump kicks on, and one by one every single light in my house turns on.  

I see this as a HomeKit deficiency (I really should be able to tell Siri what unqualified "light" should mean based on the context of where the device is located).   In the meantime, it would be great if I could map devices to HAP device types in the config file... heck anything other than a "light" would be sufficient!

**Comment by drewcovi** [comment]
If its already categorized as a switch you can. View the device details in the Home app and change the type for each device that's not a light. You can pick a fan, switch, or light. 

![img_2101](https://cloud.githubusercontent.com/assets/400278/24331786/e97e79a0-1200-11e7-8908-864415170109.PNG)

**Comment by djrobx** [comment]
I get those options for scenes, but not binary switches.  

I checked and Vera has most of the ones I would want to change as category 3, subcategory 0 (interior switch).

**Comment by djrobx** [comment]
<img width="262" alt="screen shot 2017-03-26 at 8 03 21 am" src="https://cloud.githubusercontent.com/assets/1526865/24332395/c0a4d26e-11fa-11e7-95cf-44dfceb798d5.png">
<img width="442" alt="screen shot 2017-03-26 at 8 02 19 am" src="https://cloud.githubusercontent.com/assets/1526865/24332397/c5d3f1d4-11fa-11e7-8d1d-28619308d7c4.png">

**Comment by drewcovi** [comment]
@djrobx are you using the latest from the GitHub URL? Or which version are you using?

**Comment by drewcovi** [comment]
@djrobx so short term solution, simply change the subcategory number to anything but zero. Not sure why the original code decided to set any subcategory zero to a lightbulb. But this should probably change.

**Comment by drewcovi** [comment]
This should now be resolved as of https://github.com/damianxd/homebridge-vera/commit/58287bf922f81377a6baf0f8dd2458aece329afe

**Comment by djrobx** [comment]
Applied the code update.   Muuuuuuuch better.   Thank you so much!

**Comment by tsviper** [comment]
This is no longer working on the latest release.  Looks like damianalarcon changed the behavior on apr 9th so that the subcategory has to = 4 to be selectable in homekit now.  Do you know why this change was made?  Subcategory code 4 is for a "Refrigerator".

**Comment by drewcovi** [comment]
It's only a refrigerator as of the last couple of weeks.

It used to be other. So that's why it was made.

Be a part of the solution. We look forward to your pull request.

**Comment by tsviper** [comment]
Got it.  Thanks.  I am very new to this and have only dabbled in programming over the years.  I would love to be a part of this project as I am really excited about the homekit integration with my Vera.  Just got a Pi 3 up and running with it yesterday.  Once I find out how to do pull requests I'll be happy to contribute.
