### ISSUE TITLE
Wrong temperature

### ISSUE THREAD

**Issue by ryanchucks** [damianxd/homebridge-vera#115]
Hi, the latest tempsense hotfix doesn't seem fix the wrong temperature issue as described in #101. 

Fahrenheit is still being used and converted to Celsius.

I've re-setup the system just to make sure it is not a cache issue, and installed from GitHub URL.

Thanks for all the work.

**Comment by neptunix** [comment]
I can confirm that. I've checked the response from vera device and see that temperature format comes in .TemperatureFormat property (not .temperature as used in code)

So substituting temperature by TemperatureFormat does the job. Temp start to show properly

```return(
                  {
                    rooms: data.rooms,
                    devices_by_room: devices,
                    devices_full_list: data.devices,
                    scenes: data.scenes,
                    temperature: data.TemperatureFormat
                  }```

**Comment by neptunix** [comment]
Submitted pull request. Please take if agree :)
