### ISSUE TITLE
Virtual Switches

### ISSUE THREAD

**Issue by roflcoopter** [damianxd/homebridge-vera#120]
Hi,

I am wondering if anyone is able to get the Virtual Switches from the Virtual Switch app to work with homebridge-vera? Mine does not import.

**Comment by bblacey** [comment]
If you create your virtual switch using the MIOS I_VirtualSwitch.xml, then homebridge-vera will be able to control it.  I have found the virtual switches created with the available apps do not appear on the Vera dashboard under UI7 nor can homebridge-vera control them.

**Comment by bblacey** [comment]
@roflcoopter, Did you try creating your virtual switch using the link above?  It has worked for me.

**Comment by roflcoopter** [comment]
@bblacey, sorry ive been away for easter. Ill try today and report back/close the issue

**Comment by roflcoopter** [comment]
Worked fine, thanks!
