### ISSUE TITLE
Plugin complains 'No configuration found' when attempting to run in Homebridge

### ISSUE THREAD

**Issue by roncoejr** [damianxd/homebridge-vera#123]
I can get this vera plug-in to run in standalone mode, but when executing the 'homebridge' command the startup fails with the vera plugin complaining that it cannot find a configuration.  I've made sure to put the config.js file in both the node module directory and the .veralink directory under my home directory.  I've modified the config.json file so that it has the Vera platform entry: defining the platform and its name.  I've also included the VeraIP in the bridge section.  No joy.

<img width="1159" alt="screen shot 2017-05-21 at 12 57 26 pm" src="https://cloud.githubusercontent.com/assets/25880798/26285849/cb03ef4a-3e25-11e7-94c5-a1ad8afa2f56.png">

Would appreciate your thoughts on what might be going on here.

Thank you.

**Comment by drewcovi** [comment]
Can you paste in your config.json?

**Comment by roncoejr** [comment]
My config.json is quite long, so I'll just post the relevant sections for now.  Let me know if you need to see more:

<img width="783" alt="screen shot 2017-05-21 at 1 11 50 pm" src="https://cloud.githubusercontent.com/assets/25880798/26285934/46ca1d24-3e27-11e7-8b84-3126b1e04c73.png">

<img width="403" alt="screen shot 2017-05-21 at 1 12 18 pm" src="https://cloud.githubusercontent.com/assets/25880798/26285937/4f35b0d6-3e27-11e7-815a-f8e64d67941c.png">

**Comment by drewcovi** [comment]
You need quite a bit more for your Vera platform object. Platform, name, IP address for your Vera. Check the readme

**Comment by drewcovi** [comment]
You also do not need the VeraIP key in the bridge config.

**Comment by roncoejr** [comment]
Thank you for the clues.  You know what it was?: I had the 'v' in veraIP capitalized...

Thank you again.  Should be fun to work with this.

**Comment by drewcovi** [comment]
:+1
