### ISSUE TITLE
Veralink refresh following addition of new devices in Vera

### ISSUE THREAD

**Issue by gadgetstar** [damianxd/homebridge-vera#126]
Does anyone know how to force a refresh after adding new devices or moving a device to a room in Vera?

I noticed that devices that do not have a room (No Room) are not available in HomeKit. After moving the devices to a room they were not available. I also removed the room from Home and re added it to no avail, and I rebooted the Raspberry Pi and restarted VeraLink, again to no avail.

**Comment by drewcovi** [comment]
Are you using homebridge with this as a plugin? or using just veralink in standalone?

I would recommend not using standalone.

**Comment by gadgetstar** [comment]
Hi Drew, currently as Standalone. It is working fine with the devices that were first Seen. I cannot find a Veralink (or Homebridge plugin) in the Vera Apps. Could you please point me in the right direction in case I'm being a bit thick. Cheers

**Comment by drewcovi** [comment]
Hey @gadgetstar follow the instructions on the homebridge page. If you've installed homebridge-vera you just need to make sure it's in your homebridge config file as the instructions show. This is always the better choice as it allows you to support all sorts of smart home devices outside of Vera

**Comment by gadgetstar** [comment]
Thanks Drew. all sorted. Have updated to home bridge version and set to auto start on fail or reboot. Reduced the number of devices to below 100 and all come in perfect. The Danfoss Radiator valves show up and show the current temp setting but you cannot control them. I can control the Nest and another room stat though.
Appreciate the guidance!
