### ISSUE TITLE
Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by thomashw** [damianxd/homebridge-vera#129]
This occurs when I set "includethermostat" to true and try to set the temperature. I also cannot control anything and don't receive device status after I attempt to set the temperature. If I set it to false then I can control my door lock and lights but obviously the thermostat is no longer included.

Accessory [Homebridge] Processing characteristic set: [{"aid":17,"iid":12,"value":17}] +1ms
  Accessory [Homebridge] Setting Characteristic "Target Temperature" to value 17 +0ms
  VeraLink Setting target temp value for Thermostat to 17 +9ms
  VeraLink TypeError: Cannot read property 'map' of undefined
  VeraLink     at Object.setTargetTemperature (/usr/lib/node_modules/homebridge-vera/lib/types/thermostat.js:192:36)
  VeraLink     at .<anonymous> (/usr/lib/node_modules/homebridge-vera/lib/types/thermostat.js:311:28)
  VeraLink     at emitMany (events.js:127:13)
  VeraLink     at emit (events.js:201:7)
  VeraLink     at Characteristic.setValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
  VeraLink     at Bridge.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:756:22)
  VeraLink     at Array.forEach (native)
  VeraLink     at Bridge.Accessory._handleSetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:701:8)
  VeraLink     at emitMany (events.js:127:13)
  VeraLink     at HAPServer.emit (events.js:201:7)
  VeraLink     at HAPServer._handleCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:972:10)
  VeraLink     at HAPServer.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
  VeraLink     at emitNone (events.js:86:13)
  VeraLink     at IncomingMessage.emit (events.js:185:7)
  VeraLink     at endReadableNT (_stream_readable.js:974:12)
  VeraLink     at _combinedTickCallback (internal/process/next_tick.js:80:11)
  VeraLink     at process._tickCallback (internal/process/next_tick.js:104:9) +1ms

**Comment by drewcovi** [comment]
Is it a nest? Or a zwave thermostat?

**Comment by thomashw** [comment]
It's this one: http://www.zwaveproducts.com/shop/climate-control/z-wave-thermostats/ct32-thermostat

**Comment by thomashw** [comment]
@drewcovi I spent a little bit tonight looking at this. The issue is the Characteristic.TargetHeatingCoolingState.OFF mode isn't handled in thermostat.js within the setTargetTemperature function.

As expected, after turning the thermostat on (heat, cool, or auto) there's no issue.

I don't mind fixing the issue and making a pull request, but what is the desired behaviour if the thermostat is off? We could simply ignore the request if the thermostat is in the off state. Is there a way to not display the temperature slider when the thermostat is in the off state? If we should ignore the request then it would be even better to not even provide the ability to send the request.

**Comment by tsviper** [comment]
Noticed this issue with my z-wave thermostats as well. Trying to set the temperature while in the off state locks things up for a while. I would just code it to ignore the request if thermostat is in off state like you suggested.
