### ISSUE TITLE
does not have permission to access the dev dir "/root/.node-gyp/7.10.0

### ISSUE THREAD

**Issue by chezpaul** [damianxd/homebridge-vera#130]
Plugin won't install. 
I keep getting these error during install on Raspberry 3.

Here is my [terminal log](https://pastebin.com/FGEL3Yg2)

In pastebin you can see all prior dependencies were installed... sometimes twice..  ;-)

**Comment by drewcovi** [comment]
Try using unsafe-perm. 

https://github.com/nfarina/homebridge/issues/405

**Comment by chezpaul** [comment]
That seemed to have worked, thanks. 
I still got an error, but I guess I can disregard:

make: Leaving directory '/usr/lib/node_modules/homebridge-vera/node_modules/ed25519/build'

> bignum@0.12.5 install /usr/lib/node_modules/homebridge-vera/node_modules/bignum
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://rvagg-node.s3-us-west-2.amazonaws.com/bignum/v0.12.5/bignum-v0.12.5-node-v51-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for bignum@0.12.5 and node@7.10.0 (node-v51 ABI) (falling back to source compile with node-gyp)

**Comment by drewcovi** [comment]
Yap! If it can't find a prebuilt package it falls back to build it from scratch. Which can happen if you have the very latest node and is completely fine.

**Comment by chezpaul** [comment]
Great
Thanks for the help
I'm almost there.. now I need to figure out how to built my config.json file appropriately.
