### ISSUE TITLE
Not working with IOS11

### ISSUE THREAD

**Issue by theo-69** [damianxd/homebridge-vera#139]
I just updated to IOS 11 and homebridge stopped working.
So I reinstalled with `sudo npm install -g --unsafe-perm homebridge`, still nothing, homebridge is starting but all Items are not responding and showing with !

**Comment by drewcovi** [comment]
So this is only a plug-in for homebridge. Not homebridge itself. I also upgraded today. All items working flawlessly. I’d recommend removing plugins one by one and pinpointing the issue. But pretty sure it’s not here. Been running ios11 dev betas for months as well on iPad.
