### ISSUE TITLE
Only returns 5 devices

### ISSUE THREAD

**Issue by trouty00** [damianxd/homebridge-vera#14]
just got up and running on ubuntu box but only returns 5 devices - got circa 50 devices and loads of scenes too.

**Comment by damianromanowski** [comment]
Which devices did it find? All of the same type? or a mix and match situation?

**Note:** Vera scenes will not be imported into HomeKit.

**Comment by trouty00** [comment]
now you mention it yes - all of them are plug in appliance modules, doesnt
pick up any of my fibaro dimmers or scenes etc, tried changing dimmertest
to true but fails to load

On Mon, Feb 1, 2016 at 4:16 PM, Damian Romanowski <notifications@github.com>
wrote:

> Which devices did it find? All of the same type? or a mix and match
> situation?
>
> *Note:* Vera scenes will not be imported into HomeKit.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/damianxd/homebridge-vera/issues/14#issuecomment-178049681>
> .
>



-- 
skype :stu.trout
MSN  : trouty00@hotmail.com

**Comment by trouty00** [comment]
ok - found the problem - had a couple of devices named the same - fibaro
dimmer2 creates 2 x _dimmable_light devices for whatevere reason so just
renamed and its now picked them up - although crashes pretty quickly..

Homebridge is running on port 51826.
/usr/lib/node_modules/homebridge-vera/node_modules/sync-request/index.js:31
    throw new Error(response.error.message || response.error || response);
    ^

Error: socket hang up
    at Object.doRequest [as request]
(/usr/lib/node_modules/homebridge-vera/node_modules/sync-request/index.js:31:11)
    at Object.Dimmer.getStatus
(/usr/lib/node_modules/homebridge-vera/lib/types/dimmer.js:78:31)
    at null.<anonymous>
(/usr/lib/node_modules/homebridge-vera/lib/types/dimmer.js:153:38)
    at emitTwo (events.js:100:13)
    at emit (events.js:185:7)
    at Characteristic.getValue
(/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:120:10)
    at Bridge.<anonymous>
(/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:438:20)
    at Array.forEach (native)
    at Bridge.Accessory._handleGetCharacteristics
(/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:410:8)
    at emitThree (events.js:110:13)
    at HAPServer.emit (events.js:188:7)
    at HAPServer._handleCharacteristics
(/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:659:10)
    at HAPServer.<anonymous>
(/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:172:39)
    at emitNone (events.js:80:13)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:906:12)


On Mon, Feb 1, 2016 at 4:42 PM, Stu Trout <stu.trout@gmail.com> wrote:

> now you mention it yes - all of them are plug in appliance modules, doesnt
> pick up any of my fibaro dimmers or scenes etc, tried changing dimmertest
> to true but fails to load
>
> On Mon, Feb 1, 2016 at 4:16 PM, Damian Romanowski <
> notifications@github.com> wrote:
>
>> Which devices did it find? All of the same type? or a mix and match
>> situation?
>>
>> *Note:* Vera scenes will not be imported into HomeKit.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/damianxd/homebridge-vera/issues/14#issuecomment-178049681>
>> .
>>
>
>
>
> --
> skype :stu.trout
> MSN  : trouty00@hotmail.com
>



-- 
skype :stu.trout
MSN  : trouty00@hotmail.com

**Comment by damianromanowski** [comment]
Looks like an unhandled socket exception. Line 78:
````javascript
res = HAPnode.request('GET','http://'+config.veraIP+':3480/data_request?id=variableget&DeviceNum='+device.id+'&serviceId=urn:upnp-org:serviceId:SwitchPower1&Variable=Status');
````

It's trying to get the dimmer power level. For some reason vera closed the connection on you. If you can get the ip and device id of that dimmer then plug in: `http://YOURVERAIP:3480/data_request?id=variableget&DeviceNum=YOUDEVICEID&serviceId=urn:upnp-org:serviceId:SwitchPower1&Variable=Status`  into your browser and see if you can get a response.

**Comment by damianxd** [comment]
Uhm, maybe the the script has troubles with specific dimmers while getting the status, Damian is right, if you can get the info by using your browser, I may be able to update the code for future use.
