### ISSUE TITLE
Z wave siren shown as lightbulb

### ISSUE THREAD

**Issue by stofakiller** [damianxd/homebridge-vera#143]
Hi,

I just got a siren [https://www.banggood.com/NEO-NAS-AB01Z-Z-wave-Wireless-Siren-Alarm-Sensor-Alarm-Home-Automation-Alarm-Smart-Home-Security-p-1165027.html?p=2N2307682884201407E9](https://www.banggood.com/NEO-NAS-AB01Z-Z-wave-Wireless-Siren-Alarm-Sensor-Alarm-Home-Automation-Alarm-Smart-Home-Security-p-1165027.html?p=2N2307682884201407E9) in my vera it shows as a Siren (Device file:D_Siren1.xml and D_Siren1.json) but in homekit it a lightbulb and cant be changed to eg switch, so when i use siri to turn on all light, the siren turns on :-(

Can it be shown as a siren or as a switch

**Comment by adrum** [comment]
@stofakiller I'm getting a siren toward the end of the week and will likely implement this over the weekend. After reviewing the various types of devices, would it make more sense to have it display as a speaker? The required characteristic is the mute command. 

Muted=Siren Off
Not Muted=Siren On
