### ISSUE TITLE
Standalone install error

### ISSUE THREAD

**Issue by Callero** [damianxd/homebridge-vera#146]
Trying to install on fresh install of Ubuntu Server 16.04.3 LTS

node: v9.2.0

Trying:
`npm install homebridge-vera`

Pastebin of full log:
https://pastebin.com/CcC2SwWs

End message:
+ homebridge-vera@0.7.6
added 176 packages in 23.94s

┌─────────────────────────────────────────────────────────┐
│                 npm update check failed                 │
│           Try running with sudo or get access           │
│          to the local update config store via           │
│ sudo chown -R $USER:$(id -gn $USER) /home/calle/.config │
└─────────────────────────────────────────────────────────┘

Trying to run:
`node VeraLink.js`

Throws error:

module.js:544
    throw err;
    ^

Error: Cannot find module '/home/calle/VeraLink.js'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3

**Comment by drewcovi** [comment]
Moving forward, @damianxd might have to help with the standalone version. 

This should really only be installed as a plugin to the broader Homebridge platform. I’d recommend getting the standard Homebridge up and running first.

**Comment by drewcovi** [comment]
You’re running into issues installing without Audi access. This is well documented over at the Homebridge project repo.
