### ISSUE TITLE
Roller blinds percent controls not working

### ISSUE THREAD

**Issue by mrkernels** [damianxd/homebridge-vera#159]
I have a Qubino Shutter DC that controls a roller blind. In homekit there is a dimmer slider but it's not working. Only Open/Close works. It doesn't report current % either.

I noticed in HAP-NodeJS has changed alot since the windowcovering.js was created. Perhaps there is a mismatch between these functions?

**Comment by givanildo** [comment]
For me the same thing.   And I still do not get the feedback state.

**Comment by givanildo** [comment]
Maybe because the windows covering in vera it is adjusted by:
<state id="200" service="urn:upnp-org:serviceId:SwitchPower1" variable="Status" value="1"/>
<state id="201" service="urn:upnp-org:serviceId:Dimming1" variable="LoadLevelLast" value="100"/>
<state id="202" service="urn:upnp-org:serviceId:Dimming1" variable="LoadLevelStatus" value="0"/>

**Comment by givanildo** [comment]
state id="200" service="urn:upnp-org:serviceId:SwitchPower1" variable="Status" value="1"
state id="201" service="urn:upnp-org:serviceId:Dimming1" variable="LoadLevelLast" value="100"
state id="202" service="urn:upnp-org:serviceId:Dimming1" variable="LoadLevelStatus" value="100"

**Comment by givanildo** [comment]
and the homebridge vera ... only action up down stop
....
 module.newDevice = function(device)
    {
        var self = this;
        const VERA_REF = "urn:upnp-org:serviceId:WindowCovering1";
        const VERA_ACTION =
        {
            DOWN : { ref: "Down", state : 0},
            UP : { ref: "Up", state : 1},
            STOP : { ref: "Stop", state : 2},
        };

        //// Initializing accessory
        self.component = new Accessory(device.name, uuid.generate(`device:windowcovering:${config.cardinality}:${device.id}`));
        self.component.username  = functions.genMac(`device:${config.cardinality}:${device.id}`);
        self.component.pincode   = config.pincode;
        self.component.deviceid  = device.id;

        //// Runtime states
        self.lastPosition = 0; //// Closed by default
        self.currentPositionState = VERA_ACTION.STOP.state; //// STOP by default
        self.currentTargetPosition = VERA_ACTION.DOWN.state; //// DOWN by default

        self.formatUrl = (action) =>  { return `http://${config.veraIP}:3480/data_request?id=lu_action&output_format=xml&DeviceNum=${device.id}&serviceId=${VERA_REF}&action=${action}` };

        self.setAction = (pos, callback) =>
        {
            self.currentTargetPosition = pos;
            const action = (pos === -1 ? VERA_ACTION.STOP : (pos >= self.lastPosition ? VERA_ACTION.UP : VERA_ACTION.DOWN)).ref;
            self.component.getService(Service.WindowCovering).setCharacteristic(Characteristic.PositionState, action.state);

            return HAPnode.request(
                {
                    method:'GET',
                    uri : self.formatUrl(action),
                    resolveWithFullResponse: true}
                )
                .then(function (res)
                {
                    self.component.getService(Service.WindowCovering).setCharacteristic(Characteristic.CurrentPosition, (action === VERA_ACTION.UP.ref ? 100 : 0));
                    self.component.getService(Service.WindowCovering).setCharacteristic(Characteristic.PositionState, 2); //// Stop state
                    self.lastPosition = (action == VERA_ACTION.UP.ref ? 100 : 0);
                    callback(false);
                }).catch(function (err) {
                    HAPnode.debug("Request error:"+err);
                    callback(false);
                });
        };

        self.holdAction = (level, callback) => {
            return self.setAction(-1, callback);
        };

        self.getStatus = () =>
        {
            debug("Making request for device %s", device.name);
            status = parseInt(functions.getVariable(device.id, 'status'));
            debug("Status for ", device.name, " is ", status);
            return status;
        };

**Comment by givanildo** [comment]
I don't know   !!!  sorry about my bad English

**Comment by anupchavda1** [comment]
Have the same issue. The reporting of the right status is annoying me as it then wont trigger the scene from Homekit. It sees the Device in the wrong status (ie already closed) and therefore wont trigger the scene.

**Comment by damianxd** [comment]
Hello,

Try to go here on your browser:
http://<veraIP>:3480/data_request?id=sdata
Replace <veraIP> with your Vera’s IP address.

Send me the output of that, then go to your Vera’s config and locate any device with percent variable, like the roller shutter you have. Send me the Device ID of it.

Next, I need you to do the following things:

1.- Set the device that you took the number of, to 0%
2.- Go to http://<veraIP>:3480/data_request?id=sdata again and copy that text for me
3.- Set the device to 50%
4.- Go to http://<veraIP>:3480/data_request?id=sdata again and copy the text
5.- Set the device to 100%
6.- Go to http://<veraIP>:3480/data_request?id=sdata and copy the text

Send me the device ID and the 4 texts from that page: the original with no changes, the ones with 0, 50 and 100%

**Comment by anupchavda1** [comment]
Hi

Please find attached the Zip File as requested with my 4 files.

The device ID is 307 (Living Room Curtains)

Really hope you can help!

Thanks




[Data_Request_Anup.zip](https://github.com/damianxd/homebridge-vera/files/2584712/Data_Request_Anup.zip)

**Comment by Amit86** [comment]
Hello,
I changed these from my Vera device page.
When changing from Siri or the HomeKit I can either open or close, nothing in between.
I have the same issue - this is from my sdata page:

Closed: { "name": "Vitrina Shutter", "altid": "28", "id": 145, "category": 8, "subcategory": 0, "room": 6, "parent": 1, "status": "1", "level": "100", "watts": "0.0", "kwh": "0.8400", "state": -1, "comment": "" },
Half open: { "name": "Vitrina Shutter", "altid": "28", "id": 145, "category": 8, "subcategory": 0, "room": 6, "parent": 1, "kwh": "0.8400", "level": "50", "status": "1", "watts": "0.0", "state": -1, "comment": "" }
Open: { "name": "Vitrina Shutter", "altid": "28", "id": 145, "category": 8, "subcategory": 0, "room": 6, "parent": 1, "kwh": "0.8400", "status": "1", "level": "100", "state": 4, "comment": "Vitrina Shutter: SUCCESS! Transmit was OK", "watts": "0.0" },

**Comment by Amit86** [comment]
By the way, this is what I use with HABridge to dim the shutter:
http://ip:3480/data_request?id=lu_action&output_format=json&serviceId=urn:upnp-org:serviceId:Dimming1&action=SetLoadLevelTarget&**newLoadlevelTarget=${intensity.percent}**&DeviceNum=145

Hope that helps.
