### ISSUE TITLE
All switches are treated as light

### ISSUE THREAD

**Issue by CelticWebSolutions** [damianxd/homebridge-vera#17]
Thanks for your work on this, it's really excellent to be able to control vera via Siri.

I'm having a bit of an issue though.  Basically, any device with the category 3 is treated as a light by HomeKit, Giving siri the "Turn all lights on" command turns all forms of switches on.

In Vera UI7 only devices with the category of 3 and subcategory also of 3 (so 3 for both main and sub category) are treated as lights in the All lights on / off shortcuts.

So the fact that HomeKit trees every switch as a light means that if I say "Turn all lights on", my TV comes on and even my garden gates open because they are controlled by a relay with a main category of 3.  Is there any way to force Homekit to only use switches with with a subcategory of 3 the same as Vera does for the Shortcut? 

Thanks in advance!

**Comment by damianxd** [comment]
In another post there is a request to filter which room will be sent to homekit, I will try to make it this weekend

**Comment by CelticWebSolutions** [comment]
Thanks.
I don't know much about how HomeKit works but is it supposed to be able to tell the difference between a plug and a light? 

I'd still like control of my plug switches but I'd like HomeKit to know that it's not a light when I tell it to turn on all the lights.

It looks like you should be able to select what an item does in HomeKit but all my switches only give me the choice of lights.  Even if I have to manually edit something on the home bridge side to force it to know the difference that would be fine.

**Comment by snizzleorg** [comment]
Homekit differentiales switches and lights. It is quite useful. for example now if I say "switch off the lights" siri switches my stereo off as well (and the video projector).

the home bridge-openhab plugin uses some kind of custom attribute where you can define the types of each device in the hombridge config

**Comment by CelticWebSolutions** [comment]
I wondered if it would be possible to just add a custom attribute or variable which told the plugin to use it as a switch instead of a light.  In a perfect world we could tell the plugin id's of devices (not just rooms) we wanted it to ignore along with having the ability to set a custom variable on certain devices which would tell the plugin what the device actually is so that it remained useable in HomeKit as what it actually was instead of being bunched together with similar devices.

**Comment by CelticWebSolutions** [comment]
I wondered if it would be possible to just add a custom attribute or variable which told the plugin to use it as a switch instead of a light.  

In a perfect world, the ability to add a custom variable (advanced tab, new service) to a device which altered how the plugin handled it would be great.  

That extra variable could then tell the Vera HomeKit plugin what type of device it was based on the number, E.g. set the customer variable to 1 and it's a light, set it to 2 and it's a plug socket and of course set it to 0 and it gets ignored.  I think that would lie an excellent setup which would give additional flexibility to the plugin.

I know you just made a modification to ignore entire rooms but do you think the above would be possible damianxd?  I have lights in rooms the same as plug sockets and I use both vera and HomeKit so ignoring a room isn't the perfect option for me and I'm sure many others are the same.  What do you think?

**Comment by JiPi72** [comment]
is there a solution to see the module fibaro Roller shutter ?
Where can we find the additional plug-in.
thank you for this work

**Comment by damianxd** [comment]
Switches should be treated as switches instead of lightbulbs on the latest version.
I current don't have a solution for roller shutters

**Comment by CelticWebSolutions** [comment]
Unfortunately it's now seeing all my lights as switches.  What settings does your plugin use to distinguish between light and switches?  Is it category and sub category or something else please?

**Comment by JiPi72** [comment]
Ok, thanks, but you think you will find a solution or give up ?

In advance, thanks for your answer.

Regards.

JPB

 

De : Damian Alarcon [mailto:notifications@github.com] 
Envoyé : samedi, 24 septembre 2016 15:05
À : damianxd/homebridge-vera <homebridge-vera@noreply.github.com>
Cc : JiPi72 <mail@jpbrunetti.ch>; Comment <comment@noreply.github.com>
Objet : Re: [damianxd/homebridge-vera] All switches are treated as light (#17)

 

Switches should be treated as switches instead of lightbulbs on the latest version.
I current don't have a solution for roller shutters

**Comment by damianxd** [comment]
Any subcategory higher than 0 will be treated as switch.
I will check for shutters in a future version

**Comment by CelticWebSolutions** [comment]
Thanks for the reply.  I just found the code
                case 3: // Switch
                        if(device.subcategory > 0)

and changed to 
                case 3: // Switch
                        if(device.subcategory > 3)

My lights are setup as the different subcategories from 1 - 3 and my switched are set as 4 who is apparently the refrigerator setting.  Now works absolutely perfectly, thank you! :)
