### ISSUE TITLE
После обновления vera, плагин не работает

### ISSUE THREAD

**Issue by megavoltt** [damianxd/homebridge-vera#173]
Help. Updated vera edge, the plugin starts but does not work.

**Comment by drewcovi** [comment]
Please submit issues in English. I would first attempt a restart of both systems. We haven’t seen any broader impact of updates impacting homebridge or this plugin.

**Comment by megavoltt** [comment]
Hello
1.  I have updated to the latest version and stopped working homebridge plugin on raspberry.
2. I launched two vera edges with the same settings, but with different firmware. On version 1.7.400 Homebridge is stable ,and the latest version homebridge is restarted.The screenshot of the error send.
![2019-08-17_10-59-49](https://user-images.githubusercontent.com/44338399/63230179-e98bda00-c211-11e9-8e55-9c58c9110532.png)

**Comment by drewcovi** [comment]
Please ensure you’re running homebridge without this plugin. This appears to be an issue with your install. Not this plugin. The error message says the address is already in use. This likely means you have two separate instances of homebridge.

**Comment by drewcovi** [comment]
https://github.com/nfarina/homebridge/issues/1542
