### ISSUE TITLE
Loading error

### ISSUE THREAD

**Issue by deboy69** [damianxd/homebridge-vera#182]
Plugin 'homebridge-vera' tried to register with an incorrect plugin identifier: 'homebridge-veralink'. Please report this to the developer!

No response from devices.  Homebridge wont load vera plugin or devices. 

Version .0.8.2

**Comment by drewcovi** [comment]
How did you add the plug-in? Can you send an example of your config.json

**Comment by deboy69** [comment]
"platform": "Vera",
            "name": "Vera",
            "veraIP": "XXXXXX",
            "includesensor": "True",
            "ignorerooms": [],
            "securitypoll": 2000,
            "includethermostat": false,
            "includeRGB": false,
            "garageLocks": [],
            "ignoredevices": [],
            "ignorescenes": [],
            "houseModes": false
        },

**Comment by drewcovi** [comment]
Can you remove the quotes around “True” and use true instead and report back?

**Comment by deboy69** [comment]
same error

**Comment by drewcovi** [comment]
Is it an air, or a warning? It may be separate from the fact you’re not getting any devices

**Comment by deboy69** [comment]
[12/14/2020, 5:29:05 PM] Loaded plugin: homebridge-vera@0.8.2
VeraLink initializing
[12/14/2020, 5:29:05 PM] Plugin 'homebridge-vera' tried to register with an incorrect plugin identifier: 'homebridge-veralink'. Please report this to the developer!
[12/14/2020, 5:29:05 PM] Registering platform 'homebridge-vera.Vera'
[12/14/2020, 5:29:05 PM] ---
[12/14/2020, 5:29:05 PM] Loading 3 platforms...
[12/14/2020, 5:29:05 PM] [Home] Initializing config platform...
[12/14/2020, 5:29:05 PM] [Home] Running in Service Mode
[12/14/2020, 5:29:05 PM] [Vera] Initializing Vera platform...

**Comment by drewcovi** [comment]
So yea, it’s a warning. Are you able to share your IP address? It’s an internal IP, so honestly not really a risk. Just making sure you have it properly formatted. Maybe just include it and only replace numbers with an x. You should be able to reach your Vera on the same IP. There shouldn’t be any http in the config.

**Comment by deboy69** [comment]
192.168.1.227

**Comment by drewcovi** [comment]
Is it your only platform? Seems like it’s attempting to initialize.

**Comment by deboy69** [comment]
No, but i just wiped and reinstalled homebridge and all is good

**Comment by deboy69** [comment]
Its still there just doesnt cause homebrige not to start.
