### ISSUE TITLE
Any way to treat Vera scenes as HomeKit scenes?

### ISSUE THREAD

**Issue by tsfischer** [damianxd/homebridge-vera#185]
Vera scenes show up as a switch in HomeKit. This works, but it would be nice to have the as HK scenes. I can create scenes that trigger the appropriate scene accessory switch, but then I have two of each scene. 

Is there a way to make this happen (e.g. creating the HK scene then hiding the Vera accessory for the scene?)

**Comment by drewcovi** [comment]
Oh trust me. If anyone (in the homebridge ecosystem) could, we would 😉. Typically that’s only possible in conjunction with apps today (Nanoleaf does that). But no, as far as I’m aware HAP doesn’t support scenes.
