### ISSUE TITLE
slooow

### ISSUE THREAD

**Issue by snizzleorg** [damianxd/homebridge-vera#19]
Im running this as a plugin with homebridge and it takes anywhere between tens of seconds to minutes to actually apply a change (switch something on/off) Any idea why this may be?

thanks

**Comment by damianxd** [comment]
How much time does it takes for Vera to change something when you do it from the app or the web site?

**Comment by snizzleorg** [comment]
in the vera app/web its instantaneously I also run home-assistant via vera and there also it's instantaneously...

**Comment by damianxd** [comment]
I'm not sure about that, but generally node apps are very fast. It could be the device where you are running this app, or the connection between it and your Vera device.

I have tried it with a raspberry pi and a dedicated server, on both cases I have been able to address commands to Siri between 1 to 3 seconds delay.

**Comment by snizzleorg** [comment]
strange. Its a rpi2 but home bridge did run fast when I was using it via openhab....
Maybe because too many devices ? I currently have 40... I don't need most of them in homekit but there is no way currently to exclude devices

**Comment by damianxd** [comment]
We have a device and room filter now, please refer to [this post](https://github.com/damianxd/homebridge-vera/issues/18), then check if the speed is better with less devices.

**Comment by snizzleorg** [comment]
@damianxd 
I tried but the filtered devices still show up. Do I need to delete the persist folder?

How do I make sure that I have the latest version of the plugin?

**Comment by snizzleorg** [comment]
Ok. I found out how to get the installed versions:
```
npm list -g homebridge-vera
```
Returns:
```
/usr/local/lib
└── homebridge-vera@0.0.6 
```

**Comment by snizzleorg** [comment]
can you push the most recent version to npm?

**Comment by damianxd** [comment]
It is up and running, sorry for that mistake

**Comment by snizzleorg** [comment]
still no success with the ignored devices see referenced issue: https://github.com/damianxd/homebridge-vera/issues/18.

**Comment by damianxd** [comment]
Try again with the latest version, I have deeply tested all the possibilities and I think this time should be fine

**Comment by thetwc** [comment]
I'm finding the same slow updates.  It's all working great (thank you) but it takes about 90s for the device to update. I have 58 device pulled from two Veras directly connected to the PI on the LAN, so i do think this could be the issue.

How do i get a list of device IDs so i can 'ignoredevices:"[]" ' them?

I have tried running Homebridge from the prompt to get the device list, but this is no longer working as i have it working on auto-startup and failure, hence the config files are all over the place.  
Thank you

**Comment by bblacey** [comment]
I'm also seeing extreme slowness running on an RPI2 and RPI3 against a VeraPlus.  I'm experiencing this on two separate installs in two different houses.  Top shows Node consuming over 70% of the resources and enabling verbose logging on the Vera shows non-stop http status requests.  I haven't had a chance to auger into this but I have also tried Hackworth's Vera Bridge and it is very responsive and does hog CPU.  At the risk of complete speculation, this feels like it might be some sort of status miscommunication between homebridge and the plugin that causes homebridge to constantly request status updates from the accessories.

**Comment by damianxd** [comment]
Please try to use the new dev version:

- Clone the dev repository
`git clone https://github.com/damianxd/homebridge-vera.git
git checkout dev`

- Run homekit with the dev version
`DEBUG=* /usr/local/bin/homebridge -D -P /path/to/dev/version`

**Comment by ersan** [comment]
Just tried the dev branch and it works amazingly - near-instant updates for all devices, thank you!

**Comment by damianxd** [comment]
great, I'm glad to ear that. I will soon release it as the master

**Comment by thetwc** [comment]
Sorry, do you have an idiots guide to this.

git checkout dev returns "fatal: Not a git repository (or any of the parent directories): .git"
and 
the debug returns a number of errors.  

thanks.

**Comment by ersan** [comment]
What I did was:
```
npm uninstall -g homebridge-vera
git clone https://github.com/damianxd/homebridge-vera.git
git checkout dev
npm install -g ./homebridge-vera
```

**Comment by damianxd** [comment]
The new version is out on npm, install it with 
`npm install -g homebridge-vera`
