### ISSUE TITLE
Request: Recognize Fans / Garage

### ISSUE THREAD

**Issue by drewcovi** [damianxd/homebridge-vera#20]
So this is admittedly a long shot but here we go:

How feasible would it be to recognize a device based on provided device infos, and to categorize otherwise?

Two fan dimmers come to mind:
* GE 12730
* Leviton VRF01-1LZ

And a bonus request:
* https://apps.mios.com/plugin.php?id=2998
Siri appears to auto-recognize the word garage and despite this plugin creating a "door" will not unlock / lock the garage.

A million thanks for these considerations and any insight, if i find the time ill submit my own work to assist.

**Comment by damianxd** [comment]
- Those dimmers appears as switch for you?
- Yeah, I'm aware of that problem too :/ unfortunately I haven't been able to bypass that.

**Comment by drewcovi** [comment]
The fans show up as light dimmers, which isn't surprising as Vera doesn't have a dedicated fan control type.  I only have the Leviton item.

For the second one: So no way to read device info and (either by matching the name string or otherwise) categorize it for homebridge?

**Comment by damianxd** [comment]
I guess it could be possible to do in that way... homekit supports a lot more types of devices now, but Vera is not catching up with that any time soon.

I will check if Vera allows the name of the device to have [] in the name, then I could catch that to make more types of accessories on HAP

**Comment by drewcovi** [comment]
Very cool. 

＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿
Drew Covi ◍ drewcovi.com ◍ 612.234.2684

**Comment by Valmorefr** [comment]
Awesome plugin. Thank you! Just a request/question : I'm using iOS 10 beta and I've heard HomeKit now supports more device types, like flood detectors, or light sensors. Any way you could implement that in home ridge-vera?

**Comment by damianxd** [comment]
I’m working on something, but I can’t promise much at the moment

**Comment by drewcovi** [comment]
I think this is now working. For one reason or another. Latest iOS plus this setup. I now have fans and garage after that latest PR
