### ISSUE TITLE
Homebridge Example Config

### ISSUE THREAD

**Issue by steets250** [damianxd/homebridge-vera#23]
In the config file, it contains:
            "platform": "Vera",
            "name": "Vera",
            "veraIP": "10.0.1.5",
            "includesensor": false,
            _ignorerooms_: [20,21,22],
            "securitypoll": 2000,
            "dimmertest": false

When copied directly, I get an error starting up home bridge. However, after adding quotes around ignore rooms, everything works correctly. Can you please fix this in the readme file?

**Comment by damianxd** [comment]
Nice catch :) it is fixed now
