### ISSUE TITLE
Can't set lights to a percentage

### ISSUE THREAD

**Issue by drewcovi** [damianxd/homebridge-vera#25]
In the latest version of Vera UI 7 when asking lights to set to a percentage (say 10 for instance) lights dim then ramp up to full brightness. Seems other third party apps still work, so it seems unlikely the API changed. Is there a second request sent out? I've rebooted my homebridge service. Didn't seem to help.

**Comment by drewcovi** [comment]
Is it possible there's a second request to get status that's instead triggering an action?

**Comment by damianxd** [comment]
Those are dimmers, dimmers were not set as on by default on the previous version, please update and try it with the new one
