### ISSUE TITLE
Compatible Module Vera Homebridge

### ISSUE THREAD

**Issue by JiPi72** [damianxd/homebridge-vera#27]
Hello,

The solution is good working for me. But the fibaro modules are unrecognized, have you an idea why ?
There are the fibaro roller shutter and fibaro dimmer.

Thank you for your help

JPB

**Comment by damianxd** [comment]
Hello JPB

Can you please open up your this URL
http://ip_address:3480/data_request?id=status&output_format=xml <http://ip_address:3480/data_request?id=status&output_format=xml>
change ip_address with your local Vera IP

Save the XML output and share it with me. I need the device type code for your shutters so I can add it to the one from the dimmers in the next version.

Kind regards

              <http://www.laerit.dk/>           

Damian Alarcon / Chief Technology Officer (CTO) 
damian@laerit.dk <mailto:damian@laerit.dk> / +56979982681

Webtjenesten LærIT.dk <http://xn--lrit-voa.dk/> 
CVR/SE: 29671966 | Ellehammersvej 93, 7500 Holstebro, Danmark 
http://www.laerit.dk <http://www.laerit.dk/>

**Comment by JiPi72** [comment]
Hi Damian,

Is it possible to include in your next update virtual switches on / off ( apps that exists mios plugin) to use them and send commands scenes?
Example: https://apps.mios.com/plugin.php?id=5706

A big thank you for your work, it works really well :)

**Comment by damianxd** [comment]
Scenes are working on the latest version of the app, I don't have an answer for virtual switches yet

**Comment by JiPi72** [comment]
Hello Damian, 

 

Thanks for the response.

Can you say me if it’s possible to sync all scenes between the web app Vera and the mobile app ?

 

Regards.

JPB

 

De : Damian Alarcon [mailto:notifications@github.com] 
Envoyé : samedi, 24 septembre 2016 15:02
À : damianxd/homebridge-vera <homebridge-vera@noreply.github.com>
Cc : JiPi72 <mail@jpbrunetti.ch>; State change <state_change@noreply.github.com>
Objet : Re: [damianxd/homebridge-vera] Compatible Module Vera Homebridge (#27)

 

Scenes are working on the latest version of the app, I don't have an answer for virtual switches yet

**Comment by damianxd** [comment]
What do yo mean by sync?

**Comment by JiPi72** [comment]
Hi Damian,

 

I handed the files to date and I now see the Dimmable Light.

I realized that for the moment I could not see Roller shutter and that soon there will be an update :)

 

For scenes in VERA, I do not see how Homebridge can find them?

 

This is where I got the idea to install virtual switch to start the scenes?

 

 

What do you think ?

 

Best regards, JP

 



 

 



 

De : Damian Alarcon [mailto:notifications@github.com] 
Envoyé : lundi, 26 septembre 2016 02:37
À : damianxd/homebridge-vera <homebridge-vera@noreply.github.com>
Cc : JiPi72 <mail@jpbrunetti.ch>; State change <state_change@noreply.github.com>
Objet : Re: [damianxd/homebridge-vera] Compatible Module Vera Homebridge (#27)

 

What do yo mean by sync?

**Comment by JiPi72** [comment]
Hi Damian,

I handed the files to date and I now see the Dimmable Light.
I realized that for the moment I could not see Roller shutter and that soon there will be an update :)

For scenes in VERA, I do not see how Homebridge can find them?

This is where I got the idea to install virtual switch to start the scenes?


What do you think ?

Best regards, JP

[cid:image001.jpg@01D217E0.FCB66250]


[cid:image002.jpg@01D217E0.FCB66250]

De : Damian Alarcon [mailto:notifications@github.com]
Envoyé : lundi, 26 septembre 2016 02:37
À : damianxd/homebridge-vera <homebridge-vera@noreply.github.com>
Cc : JiPi72 <mail@jpbrunetti.ch>; State change <state_change@noreply.github.com>
Objet : Re: [damianxd/homebridge-vera] Compatible Module Vera Homebridge (#27)


What do yo mean by sync?

**Comment by damianxd** [comment]
But scenes are already listed on homebridge, they look as switches and you don't need to do anything extra

**Comment by JiPi72** [comment]
So I have to do something wrong!

Can you tell me where I need to configure variable, I see them :(

 

 

in the image below, I have no scenes!

 

 



 

De : Damian Alarcon [mailto:notifications@github.com] 
Envoyé : lundi, 26 septembre 2016 11:52
À : damianxd/homebridge-vera <homebridge-vera@noreply.github.com>
Cc : JiPi72 <mail@jpbrunetti.ch>; State change <state_change@noreply.github.com>
Objet : Re: [damianxd/homebridge-vera] Compatible Module Vera Homebridge (#27)

 

But scenes are already listed on homebridge, they look as switches and you don't need to do anything extra

**Comment by JiPi72** [comment]
Hello, 

 

 <http://192.168.1.40:3480/data_request?id=action&serviceId=urn:micasaverde-com:serviceId:HomeAutomationGateway1&action=RunScene&SceneNum=16> http://192.168.1.40:3480/data_request?id=action&serviceId=urn:micasaverde-com:serviceId:HomeAutomationGateway1&action=RunScene&SceneNum=16

 

If I request this url in a web browser, the scene works ! 

If I say to Syrie : « Turn living room light on », it also works. (devices OK)

But if I say : « Please turn on scene XXX ». It doesn’t work. (scenes not OK)

Can you please just say me if I have to change one or some variable to activate or de-activate scenes ?

 

In others words, on the two pictures in attachment, you will see i have devices and scenes on the vera platform.

Devices works and are listed in homebridge but scenes are not.

 

In advance thanks for you answer and let me know if you have to know more informations.

 

Best regards.

JPB

 

 





De : Damian Alarcon [mailto:notifications@github.com] 
Envoyé : lundi, 26 septembre 2016 11:52
À : damianxd/homebridge-vera <homebridge-vera@noreply.github.com>
Cc : JiPi72 <mail@jpbrunetti.ch>; State change <state_change@noreply.github.com>
Objet : Re: [damianxd/homebridge-vera] Compatible Module Vera Homebridge (#27)

 

But scenes are already listed on homebridge, they look as switches and you don't need to do anything extra

**Comment by damianxd** [comment]
If you want to make a Scene that works with the "turn scene on XX" command, you need to make it manually on the home app. The Scenes from Vera are just switches on HomeKit, there is no way to add a whole scene from Vera as a homekit scene.
