### ISSUE TITLE
Socket hang up

### ISSUE THREAD

**Issue by Ricciolo** [damianxd/homebridge-vera#28]
Hi!
I get this error many times which cause homebridge crash.
```javascript
/usr/local/lib/node_modules/homebridge-vera/node_modules/sync-request/index.js:31
    throw new Error(response.error.message || response.error || response);
    ^

Error: socket hang up
    at Object.doRequest [as request] (/usr/local/lib/node_modules/homebridge-vera/node_modules/sync-request/index.js:31:11)
    at Object.Switch.getStatus (/usr/local/lib/node_modules/homebridge-vera/lib/types/switch.js:43:31)
```
It seems you don't catch errors which can be throws by sync-request, right?

**Comment by xeinth** [comment]
I have a similar issue, but what is really strange is that the Eve app I was using was fine, but after updating to iOS10, Eve still works but the Home App will crash with the above error message.  I have about 68 devices, and when I was installing this initially I think I had some issues with crashing occasionally I fixed thru restarting my container, but my gut is something could be overflowing or losing state when updating a bunch of devices.  Perhaps the Home App is polling in a different way.

**Comment by damianxd** [comment]
Please try to use the new dev version:

- Clone the dev repository
`git clone https://github.com/damianxd/homebridge-vera.git`
`git checkout dev`

- Run homekit with the dev version
`DEBUG=* /usr/local/bin/homebridge -D -P /path/to/dev/version`

**Comment by Ricciolo** [comment]
I get
```
ERROR LOADING PLUGIN homebridge-vera:
[9/21/2016, 8:46:57 PM] Error: Cannot find module 'debug'
```
module package is already installed. Am I missing something?

**Comment by damianxd** [comment]
Try with 
sudo npm install -g debug

**Comment by Ricciolo** [comment]
No luck. Should I put the vera plugin in a particular folder or launch homebridge from a specific folder?

**Comment by damianxd** [comment]
Just remove DEBUG=*

**Comment by Ricciolo** [comment]
Sorry but I get the same error. I'm launching
`/usr/local/bin/homebridge -D -P /root/.homebridge/homebridge-vera/`

**Comment by Ricciolo** [comment]
Ok, I've resolved. This I've set the NODE_PATH with
`export NODE_PATH=/usr/local/lib/node_modules/`
them I've launched
```
npm install request-promise -g
npm install debug -g
npm install async -g
npm install prompt -g
npm install request -g
npm install create-hash -g
```
Thanks @damianxd. It seems fast and reliable

**Comment by damianxd** [comment]
The new version is live on NPM, so just do a
`npm install -g homebridge-vera`

**Comment by Ricciolo** [comment]
Great 👍
