### ISSUE TITLE
Options in home bridge mode

### ISSUE THREAD

**Issue by mda30** [damianxd/homebridge-vera#32]
Hi, 3 questions if I may:
1. Is it possible to either turn on Bridged mode to make each device its own server or specific rooms and devices to ignore when running in homebridge mode? adding those parameters to ~/.homebridge/config.json not not seem to work.
2. Is there any way to make scenes (but only select scenes) appear?
3. I have 2 Veras (both Vera 3 IU5) that are not bridged to each other. Is there any way to set things up so devices and scenes from both Veras appear to homekit?

Thanks!

**Comment by damianxd** [comment]
1.- No it's not... you can do that only on the standalone mode
2.- Scenes are now active on the current version (0.5.0) from NPM
3.- Have you tried to add two platforms on the homebridge config?
```
    "platforms": [
        {
            "platform" : "Vera 1",
            "name" : "Vera 1",
            "veraIP" : "10.0.1.1",
            "includesensor": false
        },
       {
            "platform" : "Vera 2",
            "name" : "Vera 2",
            "veraIP" : "10.0.1.2",
            "includesensor": false
        }
    ],
```

**Comment by mda30** [comment]
@damianxd Thanks. 

If i have my primary vera in the config (alone or with the second vera) Homebridge appears to startup ok but my iOS homekit apps (Home and MyTouchHome on iPhone 7 iOS 10 on wifi) error with "Could't add Homebridge. Home couldn't connect to this accessory". 

If only my second vera is in the config i can can connect fine.

Here is all i see while trying to pair with debug on:
```
  EventedHTTPServer [::ffff:192.168.1.161] New connection from client +1m
  EventedHTTPServer [::ffff:192.168.1.161] HTTP server listening on port 50802 +2ms
  EventedHTTPServer [::ffff:192.168.1.161] HTTP request: /pair-setup +8ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-setup +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair step 1/5 +2ms
  EventedHTTPServer [::ffff:192.168.1.161] HTTP Response is finished +22ms
  EventedHTTPServer [::ffff:192.168.1.161] HTTP request: /pair-setup +19s
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-setup +0ms
  HAPServer [CC:22:3D:E3:CE:30] Pair step 2/5 +38ms
  EventedHTTPServer [::ffff:192.168.1.161] HTTP Response is finished +19ms
  EventedHTTPServer [::ffff:192.168.1.161] HTTP request: /pair-setup +73ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-setup +0ms
  HAPServer [CC:22:3D:E3:CE:30] Pair step 3/5 +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair step 4/5 +9ms
  HAPServer [CC:22:3D:E3:CE:30] Pair step 5/5 +1ms
  Accessory [Homebridge] Paired with client FDE0E409-D28B-4760-9BBE-60E3DA3017E4 +1ms
  EventedHTTPServer [::ffff:192.168.1.161] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.1.161] Client connection closed +246ms
  EventedHTTPServer [::ffff:192.168.1.161] HTTP connection was closed +2ms
  EventedHTTPServer [::ffff:192.168.1.161] HTTP server was closed +0ms
  EventedHTTPServer [::ffff:192.168.1.161] New connection from client +992ms
  EventedHTTPServer [::ffff:192.168.1.161] HTTP server listening on port 50805 +0ms
  EventedHTTPServer [::ffff:192.168.1.161] HTTP request: /pair-verify +2ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +1ms
  EventedHTTPServer [::ffff:192.168.1.161] HTTP Response is finished +4ms
  EventedHTTPServer [::ffff:192.168.1.161] HTTP request: /pair-verify +87ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 2/2 +0ms
  HAPServer [CC:22:3D:E3:CE:30] Client FDE0E409-D28B-4760-9BBE-60E3DA3017E4 verification complete +3ms
  EventedHTTPServer [::ffff:192.168.1.161] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.1.161] HTTP request: /accessories +171ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: GET /accessories +0ms
  EventedHTTPServer [::ffff:192.168.1.161] HTTP Response is finished +105ms
  EventedHTTPServer [::ffff:192.168.1.161] HTTP request: /pairings +1s
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pairings +0ms
  HAPServer [CC:22:3D:E3:CE:30] Removing pairing info for client +1ms
  Accessory [Homebridge] Unpairing with client FDE0E409-D28B-4760-9BBE-60E3DA3017E4 +0ms
  EventedHTTPServer [::ffff:192.168.1.161] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.1.161] Client connection closed +131ms
  EventedHTTPServer [::ffff:192.168.1.161] HTTP connection was closed +0ms
  EventedHTTPServer [::ffff:192.168.1.161] HTTP server was closed +1ms
```

Both veras are reachable from my homebridge machine. Could something be timing out?

A curl on data_request?id=user_data&output_format=xml to the primary vera takes 2.139 seconds to respond and doing the same to the secondary vera takes only 1.355 seconds to respond (the primary vera has many more devices and scenes than the secondary).

**Comment by Juppers** [comment]
Can you run the standalone version on the same server as homebridge?

**Comment by drewcovi** [comment]
@Juppers I'm not certain if @damianxd has worked on the standalone version in a while, I've only been focusing on the homebridge plugin approach.  not sure what the benefit of running it standalone is TBH...

**Comment by damianxd** [comment]
You should be able to run both, but I haven't tested

**Comment by Juppers** [comment]
Yes, you can run them both I discovered. The benefit is the standalone version lets you ignore devices so I don't expose unneeded scenes and devices to the home app and by extension the less technical folks in the house that don't know that shouldn't touch that.

**Comment by drewcovi** [comment]
Worth noting @juppers that you can ignore devices and scenes in both versions. Not sure if you're referencing an older version.

**Comment by drewcovi** [comment]
closing for now as I don't see any remaining issue. Note: you can ignore devices and scenes in the standard homebridge plugin mode.
