### ISSUE TITLE
Support for dimmer switches?

### ISSUE THREAD

**Issue by purviewdev** [damianxd/homebridge-vera#33]
I think this is an issue related to the lack of dimmer switches, but am not sure.  I've provided the Vera output and the devices that are registered by VeraLink.js.  The devices that are not registering are dimmable switches (GE).

`{ "full": 1, "version": "*1.5.622*", "model": "SERCOMM NA401", "zwave_heal": 1, "temperature": "F", "serial_number": "18175\n", "fwd1": "fwd1.mios.com", "fwd2": "fwd2.mios.com", "sections": [ { "name": "My Home", "id": 1 } ], "rooms": [ { "name": "1st Floor Foyer", "id": 7, "section": 1 }, { "name": "2nd Floor Foyer", "id": 8, "section": 1 }, { "name": "Dining Room", "id": 6, "section": 1 }, { "name": "Family Room", "id": 2, "section": 1 }, { "name": "Front Porch", "id": 10, "section": 1 }, { "name": "Garage", "id": 9, "section": 1 }, { "name": "Kitchen", "id": 1, "section": 1 }, { "name": "Library", "id": 5, "section": 1 }, { "name": "Pool Bathroom", "id": 4, "section": 1 }, { "name": "Sun Room", "id": 3, "section": 1 } ], "scenes": [ { "name": "Interior Lights Off", "id": 3, "room": 0, "state": -1, "comment": "", "active": 0 }, { "active": 0, "name": "Lock House", "id": 1, "room": 0 }, { "active": 0, "name": "New scene", "id": 7, "room": 0 }, { "name": "Outside Lights Off", "id": 5, "room": 0, "active": 1, "state": -1, "comment": "" }, { "name": "Outside Lights On", "id": 4, "room": 0, "active": 0 }, { "name": "Soft Lights Up - 1st Floor", "id": 6, "room": 0, "state": -1, "comment": "", "active": 1 }, { "active": 1, "name": "Unlock House", "id": 2, "room": 0, "state": -1, "comment": "" } ], "devices": [ { "name": "13495 Rustling Oaks Drive", "altid": "loc.67dd24f0-9f25-11e4-abde-22000b59088f", "id": 21, "category": 5, "subcategory": -1, "room": 0, "parent": 19, "status": "1" }, { "name": "2nd Floor Hallway (wing) CO", "altid": "co.18B43000002A5750", "id": 45, "category": 4, "subcategory": 5, "room": 0, "parent": 19, "tripped": "0", "lasttrip": "0", "armed": "0", "batterylevel": "92" }, { "name": "2nd Floor Hallway (wing) Smoke", "altid": "smoke.18B43000002A5750", "id": 44, "category": 4, "subcategory": 4, "room": 0, "parent": 19, "tripped": "0", "lasttrip": "0", "armed": "0", "batterylevel": "92" }, { "name": "2nd Floor Main Hallway Recessed Lights", "altid": "25", "id": 4, "category": 2, "subcategory": 0, "room": 8, "parent": 1, "status": "0", "level": "0", "state": -1, "comment": "" }, { "name": "Basement CO", "altid": "co.18B430000028313F", "id": 37, "category": 4, "subcategory": 5, "room": 0, "parent": 19, "tripped": "0", "lasttrip": "0", "armed": "0", "batterylevel": "93" }, { "name": "Basement Smoke", "altid": "smoke.18B430000028313F", "id": 36, "category": 4, "subcategory": 4, "room": 0, "parent": 19, "tripped": "0", "lasttrip": "0", "armed": "0", "batterylevel": "93" }, { "name": "Bathroom Exterior Door", "altid": "38", "id": 13, "category": 7, "subcategory": 0, "room": 4, "parent": 1, "pincodes": "<VERSION=3>78\t1,1,,,,Code 1;\t2,1,,,,Code 2;\t3,0;\t4,0;\t5,0;\t6,0;\t7,0;\t8,0;\t9,0;\t10,0;\t11,0;\t12,0;\t13,0;\t14,0;\t15,0;\t16,0;\t17,0;\t18,0;\t19,0;\t20,0;\t21,0;\t22,0;\t23,0;\t24,0;\t25,0;\t26,0;\t27,0;\t28,0;\t29,0;\t30,0;\t", "status": "0", "locked": "0", "batterylevel": "77", "state": -1, "comment": "" }, { "name": "Bedroom", "altid": "therm.02AA01AC45140BM8", "id": 23, "category": 5, "subcategory": -1, "room": 0, "parent": 19, "fanmode": "Auto", "mode": "CoolOn", "heatsp": "68", "coolsp": "74", "batterylevel": "100", "temperature": "74", "fan": "On", "hvacstate": "Cooling" }, { "name": "Bedroom CO", "altid": "co.18B430000029B335", "id": 47, "category": 4, "subcategory": 5, "room": 0, "parent": 19, "tripped": "0", "lasttrip": "0", "armed": "0", "batterylevel": "91" }, { "name": "Bedroom Humidity", "altid": "humid.02AA01AC45140BM8", "id": 25, "category": 16, "subcategory": -1, "room": 0, "parent": 19, "humidity": "40" }, { "name": "Bedroom Smoke", "altid": "smoke.18B430000029B335", "id": 46, "category": 4, "subcategory": 4, "room": 0, "parent": 19, "tripped": "0", "lasttrip": "0", "armed": "0", "batterylevel": "91" }, { "name": "Ben (Bedroom) CO", "altid": "co.18B43000002985B1", "id": 39, "category": 4, "subcategory": 5, "room": 0, "parent": 19, "tripped": "0", "lasttrip": "0", "armed": "0", "batterylevel": "93" }, { "name": "Ben (Bedroom) Smoke", "altid": "smoke.18B43000002985B1", "id": 38, "category": 4, "subcategory": 4, "room": 0, "parent": 19, "tripped": "0", "lasttrip": "0", "armed": "0", "batterylevel": "93" }, { "name": "Claire (Bedroom) CO", "altid": "co.18B43000002A5DBD", "id": 29, "category": 4, "subcategory": 5, "room": 0, "parent": 19, "tripped": "0", "lasttrip": "0", "armed": "0", "batterylevel": "82" }, { "name": "Claire (Bedroom) Smoke", "altid": "smoke.18B43000002A5DBD", "id": 28, "category": 4, "subcategory": 4, "room": 0, "parent": 19, "tripped": "0", "lasttrip": "0", "armed": "0", "batterylevel": "82" }, { "name": "Dining Room", "altid": "40", "id": 15, "category": 2, "subcategory": 0, "room": 6, "parent": 1, "status": "0", "level": "0", "state": -1, "comment": "" }, { "name": "Dining Room", "altid": "therm.02AA01AC281406HW", "id": 22, "category": 5, "subcategory": -1, "room": 0, "parent": 19, "fanmode": "Auto", "heatsp": "68", "batterylevel": "100", "coolsp": "74", "fan": "On", "mode": "CoolOn", "hvacstate": "Cooling", "temperature": "75" }, { "name": "Dining Room Humidity", "altid": "humid.02AA01AC281406HW", "id": 24, "category": 16, "subcategory": -1, "room": 0, "parent": 19, "humidity": "42" }, { "name": "Door Lock Garage", "altid": "44", "id": 43, "category": 7, "subcategory": 0, "room": 9, "parent": 1, "pincodes": "<VERSION=3>2\t1,1,,,****,Code 1;\t2,1,,,****,Code 2;\t3,0;\t4,0;\t5,0;\t6,0;\t7,0;\t8,0;\t9,0;\t10,0;\t11,0;\t12,0;\t13,0;\t14,0;\t15,0;\t16,0;\t17,0;\t18,0;\t19,0;\t", "locked": "0", "status": "0", "batterylevel": "68", "state": -1, "comment": "" }, { "name": "Downstairs CO", "altid": "co.18B43000002827BA", "id": 31, "category": 4, "subcategory": 5, "room": 0, "parent": 19, "tripped": "0", "lasttrip": "0", "armed": "0", "batterylevel": "90" }, { "name": "Downstairs Smoke", "altid": "smoke.18B43000002827BA", "id": 30, "category": 4, "subcategory": 4, "room": 0, "parent": 19, "tripped": "0", "lasttrip": "0", "armed": "0", "batterylevel": "90" }, { "name": "Family Room Recessed Light", "altid": "34", "id": 9, "category": 2, "subcategory": 0, "room": 2, "parent": 1, "status": "1", "level": "30", "state": -1, "comment": "" }, { "name": "Family Room TV Spot Lights", "altid": "33", "id": 8, "category": 2, "subcategory": 0, "room": 2, "parent": 1, "level": "30", "status": "1", "state": -1, "comment": "" }, { "name": "Foyer Orb Light Fixture", "altid": "37", "id": 12, "category": 3, "subcategory": 0, "room": 7, "parent": 1, "status": "0", "state": -1, "comment": "" }, { "name": "Foyer Recessed Lighting", "altid": "36", "id": 11, "category": 3, "subcategory": 0, "room": 7, "parent": 1, "status": "1", "state": -1, "comment": "" }, { "name": "Front Porch Recessed Lights", "altid": "7", "id": 3, "category": 2, "subcategory": 0, "room": 10, "parent": 1, "level": "0", "status": "0", "state": -1, "comment": "" }, { "name": "Garage (Upper)", "altid": "42", "id": 50, "category": 3, "subcategory": 0, "room": 0, "parent": 1, "status": "1", "state": -1, "comment": "" }, { "name": "Garage (Upper)", "altid": "41", "id": 51, "category": 3, "subcategory": 0, "room": 0, "parent": 1, "status": "1", "state": -1, "comment": "" }, { "name": "Hallway Master Bedroom (Upstairs) CO", "altid": "co.18B430000027063C", "id": 33, "category": 4, "subcategory": 5, "room": 0, "parent": 19, "tripped": "0", "lasttrip": "0", "armed": "0", "batterylevel": "90" }, { "name": "Hallway Master Bedroom (Upstairs) Smoke", "altid": "smoke.18B430000027063C", "id": 32, "category": 4, "subcategory": 4, "room": 0, "parent": 19, "tripped": "0", "lasttrip": "0", "armed": "0", "batterylevel": "90" }, { "name": "Kitchen Desk Recessed Light", "altid": "30", "id": 5, "category": 2, "subcategory": 0, "room": 1, "parent": 1, "level": "30", "status": "1", "state": -1, "comment": "" }, { "name": "Kitchen Hallway", "altid": "31", "id": 6, "category": 2, "subcategory": 0, "room": 1, "parent": 1, "level": "30", "status": "1", "state": -1, "comment": "" }, { "name": "Kitchen Recessed Lighting", "altid": "43", "id": 42, "category": 2, "subcategory": 0, "room": 1, "parent": 1, "status": "1", "level": "30", "state": -1, "comment": "" }, { "name": "Kitchen Table", "altid": "32", "id": 7, "category": 2, "subcategory": 0, "room": 1, "parent": 1, "level": "40", "status": "1", "state": -1, "comment": "" }, { "name": "Library Recessed Lights", "altid": "39", "id": 14, "category": 2, "subcategory": 0, "room": 5, "parent": 1, "status": "0", "level": "0", "state": -1, "comment": "" }, { "name": "Master Bedroom CO", "altid": "co.18B43000002E1DEF", "id": 49, "category": 4, "subcategory": 5, "room": 0, "parent": 19, "tripped": "0", "lasttrip": "0", "armed": "0", "batterylevel": "86" }, { "name": "Master Bedroom Smoke", "altid": "smoke.18B43000002E1DEF", "id": 48, "category": 4, "subcategory": 4, "room": 0, "parent": 19, "tripped": "0", "lasttrip": "0", "armed": "0", "batterylevel": "86" }, { "name": "Nest", "altid": "", "id": 19, "category": 0, "subcategory": -1, "room": 0, "parent": 0 }, { "name": "Office CO", "altid": "co.18B43000002ADBCA", "id": 27, "category": 4, "subcategory": 5, "room": 0, "parent": 19, "tripped": "0", "lasttrip": "0", "armed": "0", "batterylevel": "91" }, { "name": "Office Smoke", "altid": "smoke.18B43000002ADBCA", "id": 26, "category": 4, "subcategory": 4, "room": 0, "parent": 19, "tripped": "0", "lasttrip": "0", "armed": "0", "batterylevel": "91" }, { "name": "Porch Door Fixtures", "altid": "35", "id": 10, "category": 3, "subcategory": 0, "room": 10, "parent": 1, "status": "0", "state": -1, "comment": "" }, { "name": "Sonos", "altid": "", "id": 20, "category": 15, "subcategory": -1, "room": 0, "parent": 0, "online": "0", "transportstate": "STOPPED", "currentplaymode": "NORMAL", "currentstatus": "Offline", "currenttitle": "", "currentartist": "", "currentalbum": "", "currentalbumart": "http:\/\/192.168.189.189:80\/cmh\/skins\/default\/icons\/Sonos.png", "volume": "0", "mute": "0" }, { "name": "Topher (Bedroom) CO", "altid": "co.18B43000002A7A6E", "id": 41, "category": 4, "subcategory": 5, "room": 0, "parent": 19, "tripped": "0", "lasttrip": "0", "armed": "0", "batterylevel": "92" }, { "name": "Topher (Bedroom) Smoke", "altid": "smoke.18B43000002A7A6E", "id": 40, "category": 4, "subcategory": 4, "room": 0, "parent": 19, "tripped": "0", "lasttrip": "1447790540", "armed": "0", "batterylevel": "92" }, { "name": "Upstairs (2nd Floor Bathroom) CO", "altid": "co.18B43000002A6901", "id": 35, "category": 4, "subcategory": 5, "room": 0, "parent": 19, "tripped": "0", "lasttrip": "0", "armed": "0", "batterylevel": "93" }, { "name": "Upstairs (2nd Floor Bathroom) Smoke", "altid": "smoke.18B43000002A6901", "id": 34, "category": 4, "subcategory": 4, "room": 0, "parent": 19, "tripped": "0", "lasttrip": "0", "armed": "0", "batterylevel": "93" } ], "categories": [ { "name": "Dimmable Light", "id": 2 }, { "name": "Switch", "id": 3 }, { "name": "Sensor", "id": 4 }, { "name": "Thermostat", "id": 5 }, { "name": "Door lock", "id": 7 }, { "name": "A\/V", "id": 15 }, { "name": "Humidity Sensor", "id": 16 } ], "ir": 0, "irtx": "", "loadtime": 1474168816, "dataversion": 168918386, "state": -1, "comment": "" }`

These are the devices that register with VeraLink.js:

`
VeraLink Using url: http://192.168.189.189:3480/data_request?id=lu_sdata +0ms
VeraLink ------ Lock Added: Bathroom Exterior Door ID:13 +4ms
VeraLink ------ Lock Added: Door Lock Garage ID:43 +7ms
VeraLink ------ Switch Added: Foyer Orb Light Fixture ID:12 +3ms
VeraLink ------ Switch Added: Foyer Recessed Lighting ID:11 +1ms
VeraLink ------ Switch Added: Garage (Upper) ID:50 +1ms
VeraLink ------ Switch Added: Garage (Upper2) ID:51 +0ms
VeraLink ------ Switch Added: Porch Door Fixtures ID:10 +1ms
`

**Comment by purviewdev** [comment]
I'm willing to sponsor this feature for a $200 Amazon gift card. I can provide remote access to my Mac with NodeJS which talks to my Vera with numerous dimmers.

**Comment by damianxd** [comment]
I'm currently working on a new version of the core files, I will try to release it today and then later I could check out your specific problem

**Comment by JiPi72** [comment]
thank you for your availability, cannot wait to see your updated :)

**Comment by ersan** [comment]
Amazing!  I look forward to it as well.

**Comment by ersan** [comment]
Literally just noticed that "dimmertest" enables the dimmer switches...  Boy do I feel dumb.  I guess my only issue with this is that it is extremely slow to update, each device takes 800ms or more - I think the old VeraHomeKitBridge I used just sat there waiting for device status changes rather than polling every single device when HomeKit requested status updates, perhaps that's a better way to go?

**Comment by damianxd** [comment]
The dimmers are now turned on by default on the new version
