### ISSUE TITLE
Vera Time out

### ISSUE THREAD

**Issue by wildechild55** [damianxd/homebridge-vera#36]
Just new to all of this but I keep getting this error, homebridge times out looking for the vera, I have checked the ip and its correct.. any idea? Sorry for the NOOB question! haha

pi@raspberrypi:~ $ nano ~/.homebridge/config.json
pi@raspberrypi:~ $ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[9/23/2016, 5:42:56 PM] Loaded plugin: homebridge-vera
VeraLink initializing
[9/23/2016, 5:42:56 PM] Registering platform 'homebridge-veralink.Vera'
[9/23/2016, 5:42:56 PM] ---
[9/23/2016, 5:42:56 PM] Loaded config.json with 0 accessories and 1 platforms.
[9/23/2016, 5:42:56 PM] ---
[9/23/2016, 5:42:56 PM] Loading 1 platforms...
[9/23/2016, 5:42:56 PM] [Vera] Initializing Vera platform...
/usr/local/lib/node_modules/homebridge-vera/node_modules/sync-request/index.js:31
    throw new Error(response.error.message || response.error || response);
    ^

Error: connect ETIMEDOUT 192.168.100.191:3480
    at Object.doRequest [as request] (/usr/local/lib/node_modules/homebridge-vera/node_modules/sync-request/index.js:31:11)
    at Object.module.getVeraInfo (/usr/local/lib/node_modules/homebridge-vera/lib/functions.js:8:23)
    at Object.VeraLinkPlatform (/usr/local/lib/node_modules/homebridge-vera/index.js:41:36)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:273:32)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:71:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
pi@raspberrypi:~ $

**Comment by damianxd** [comment]
Check if your Vera device is really on that IP: 192.168.100.191

**Comment by wildechild55** [comment]
I checked through the router and the vera console and it says its the correct ip, if i change the ip to anything else it fails immediately. If I use this IP is take 2-3 mins to fail.. Could it be a firewall issue?

**Comment by wildechild55** [comment]
Can you use this with Vera Ul7 or does it need to be Ul5?﻿

**Comment by damianxd** [comment]
Can you do a 
`ping 192.168.100.191`
from the device where homebridge is?
UI7 is the one I'm using to develop this, I don't know if UI5 works

**Comment by wildechild55** [comment]
I reset my network, and router and took all the firewalls down just to be sure (so the Ip Changed) and if I type
Ping 192.168.1.11 I get 
PING 192.168.1.11 (192.168.1.11): 56 data bytes
64 bytes from 192.168.1.11: icmp_seq=0 ttl=64 time=4.228 ms
64 bytes from 192.168.1.11: icmp_seq=1 ttl=64 time=3.939 ms
64 bytes from 192.168.1.11: icmp_seq=2 ttl=64 time=3.464 ms
and the icmp_seq=# just gets larger.
I think something must be wrong with vera? I cannot connect to it via ssh, or http using the 
http://[ip address]:3480/data_request?id=user_data command. Its weird though as it working with my vera, and veramate app and works with the www.getvera.com web UL.
any thoughts?

**Comment by wildechild55** [comment]
I reset my network and router, and took down the firewalls just incase (so the Ip has changed)
but if I type ping 192.168.1.11 I get
pi@raspberrypi:~ $ ping 192.168.1.11
ping: icmp open socket: Operation not permitted
pi@raspberrypi:~ $ 
thoughts?

**Comment by damianxd** [comment]
What version of Vera do you have?

**Comment by wildechild55** [comment]
Veralite Current version: 1.7.855
I was almost thinking of flashing the vera to factory settings and seeing if its something there?

**Comment by damianxd** [comment]
I have no idea what could the problem be, but you need to have access to
http://ip_address:3480/data_request?id=status&output_format=xml
Otherwise this won't work at all

**Comment by wildechild55** [comment]
Thanks for your time, got it working, I guess its important to note if your a noob and have your Secure your Vera option selected in your user settings this won't work! Everything works great now!
