### ISSUE TITLE
Crashing with ENETUNREACH error

### ISSUE THREAD

**Issue by mda30** [damianxd/homebridge-vera#38]
@damianxd running the newest node, nom, homebridge and homebridge-vera i got an exception below and even though i was running home bridge with forever and forever showed the process running, it stopped working after this.

data:    /usr/local/bin/homebridge:38608 - Unhandled rejection RequestError: Error: connect ENETUNREACH 192.168.1.152:3480 - Local (0.0.0.0:56369)
data:    /usr/local/bin/homebridge:38608 -     at new RequestError (/usr/local/lib/node_modules/homebridge-vera/node_modules/request-promise/lib/errors.js:14:15)
data:    /usr/local/bin/homebridge:38608 -     at Request.RP$callback [as _callback](/usr/local/lib/node_modules/homebridge-vera/node_modules/request-promise/lib/rp.js:60:25)
data:    /usr/local/bin/homebridge:38608 -     at self.callback (/usr/local/lib/node_modules/homebridge-vera/node_modules/request/request.js:187:22)
data:    /usr/local/bin/homebridge:38608 -     at emitOne (events.js:96:13)
data:    /usr/local/bin/homebridge:38608 -     at Request.emit (events.js:188:7)
data:    /usr/local/bin/homebridge:38608 -     at Request.onRequestError (/usr/local/lib/node_modules/homebridge-vera/node_modules/request/request.js:813:8)
data:    /usr/local/bin/homebridge:38608 -     at emitOne (events.js:96:13)
data:    /usr/local/bin/homebridge:38608 -     at ClientRequest.emit (events.js:188:7)
data:    /usr/local/bin/homebridge:38608 -     at Socket.socketErrorListener (_http_client.js:308:9)
data:    /usr/local/bin/homebridge:38608 -     at emitOne (events.js:96:13)
data:    /usr/local/bin/homebridge:38608 -     at Socket.emit (events.js:188:7)
data:    /usr/local/bin/homebridge:38608 -     at emitErrorNT (net.js:1271:8)
data:    /usr/local/bin/homebridge:38608 -     at _combinedTickCallback (internal/process/next_tick.js:74:11)
data:    /usr/local/bin/homebridge:38608 -     at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by damianxd** [comment]
Try with the latest version (0.5.2)
