### ISSUE TITLE
Security devices not showing anymore 

### ISSUE THREAD

**Issue by Valmorefr** [damianxd/homebridge-vera#39]
Hi,

Justhad to resintall my server. I reinstalled home bridge vera, but now my security devices are only showing up as thermo sensors (I used to have a movement sensor, a door opening sensor, flood sensor...). Am I doing something wrong?

Cheers,
Sylvain

**Comment by damianxd** [comment]
Security sensors are disabled at the moment for stability reasons. I will add them in a next release

**Comment by Valmorefr** [comment]
Hi,

Any chance security devices are coming back in the not so distant future?

Cheers

**Comment by damianxd** [comment]
I want to add them back but when I do, the Vera device gets flooded with too many calls so it drops dead after a while. I need to make a plugin on Vera first so the device can send the update to homebridge, instead of homebridge to poke for updates every second.



Enviado desde mi iPhone

**Comment by Valmorefr** [comment]
Hi there! Any news on that front?

**Comment by drewcovi** [comment]
We could probably reintroduce this now that we use cached status rather than individual calls.

**Comment by Valmorefr** [comment]
Any chance of you guys managing to re-implement those devices anytime soon? Thanks a lot.

**Comment by drewcovi** [comment]
We have sensors now on Master
