### ISSUE TITLE
Siri requests timeout

### ISSUE THREAD

**Issue by Ricciolo** [damianxd/homebridge-vera#40]
Hi @damianxd,
I saw you rewrite the plugin in async way and now it works very well.
Nevertheless I regularly have some troubles when making requests using Siri. She often answers me that she cannot make the request. If I try a second time, it works. I think that Siri has a very low request timeout (like 1 second) in order to give a good user experience.
For the temperatue sensor, for example, I think the problem is that when Siri asks to the plugin, the plugin asks to Vera but it's not fast enough (I'm using cables).

May be a good idea to regularly poll Vera in other to get the temperature, cache the value, and answer to homekit using the cached value and not making the request. For switches, it can use a queue in order to accept the action (on, off) and answer immediately to homekit. In the meanwhile a worker processes the queue in a reliable way.

What do you think about?

**Comment by damianxd** [comment]
Try with the latest version (0.5.2)
