### ISSUE TITLE
supported devices

### ISSUE THREAD

**Issue by rksana** [damianxd/homebridge-vera#41]
Is only Z-wave devices supported with this? I have Z-wave Switches, IP Camera, Z-wave Thermostat and Ecobee3 Thermosta,  GE Security (Serial to USB) devices..  I was able to see only light switches in Homekit configuration.. 

Anyway ignore vera scenes not getting imported to Homekit?

Thanks for help

**Comment by damianxd** [comment]
scenes do work on the latest version, but they are treated as switches. Thermostat is on beta phase right now.
There is no support for cameras on homebridge right now and I don't know much about Serial to USB devices

**Comment by tregusti** [comment]
I just wanted to have a clarification on if this package handles non z-wave devices.

Vera plus sports zigbee, z-wave and some other protocols, but the readme here states z-wave only.
