### ISSUE TITLE
Finding my room numbers

### ISSUE THREAD

**Issue by jdjammer** [damianxd/homebridge-vera#42]
I want to ignore some of my rooms on the config.json file, but I can't find out how to identify the number on certain rooms.  How can I find out what rooms have which number?

Thank you!

**Comment by briandye** [comment]
In Vera UI if you go into the advanced setting of a device you should see Room: listed with a numeric value assigned. "No room" has value of zero.

**Comment by bitmerchandise** [comment]
or put this in your browser http://vera_ip:3480/data_request?id=user_data&output_format=xml and scroll down to <rooms> </rooms>section.

**Comment by jdjammer** [comment]
Thank you Brian!  Now, for whatever reason the config.json "ignorerooms" setting is not actually ignoring the rooms.  Anyone else run into that?

**Comment by jdjammer** [comment]
Thank you bit merchandise as well, that also helped!

**Comment by jdjammer** [comment]
Just saw that the ignorerooms only works in standalone mode.. That answered my second question.  Thank you for your help!
