### ISSUE TITLE
Thermostat not found

### ISSUE THREAD

**Issue by bitmerchandise** [damianxd/homebridge-vera#45]
Thank you for all the work, it's improved a lot and ignoring devices is excellent...

I tried the newest version but it doesn't pick up my thermostat.
I don't even see it process it in homebridge-out.log 
in vera it is seen as device_type urn:schemas-upnp-org:device:HVAC_ZoneThermostat:1
device_file D_HVAC_ZoneThermostat1.xml

npm list yields

npm list -g homebridge-vera

└── homebridge-vera@0.5.2 

Thanks for looking into this

**Comment by bitmerchandise** [comment]
Note: I noticed I was not on the newest version so I updated and still the same results

npm list -g homebridge-vera
versions/node/v6.0.0/lib
└── homebridge-vera@0.5.3

**Comment by stofakiller** [comment]
Hi,

Mine (Danfoss) is also missing:
urn:schemas-upnp-org:device:Heater:1
D_Heater1.xml

Im also on 0.5.3

Regards,
Jan

**Comment by stofakiller** [comment]
Wow, now it works :-)

In the file functions.js, i just removed:

if(config.includethermostat)

And restarted the homebridge :-)

So something is supposed to be in the config.json

Regards,
Jan

**Comment by bitmerchandise** [comment]
Sorry, what works?
Does homebridge-vera work now or can you see the thermostat now?
I tried commenting if(config.includethermostat) (commented the IF and the matching brace). 
Still doesn't see the thermostat.
Is there something else that you did? 
I didn't reset homekit, I am not at home at the moment. Did you reset homekit?

Thanks

            //        if(config.includethermostat){
                        var Thermostat            = require("./types/thermostat.js")(HAPnode,config,module);
                        HAPnode.debug('------ Thermostat Added: %s', device.name + ' ID:' +device.id);
                        accessories.push(Thermostat.newDevice(device, verainfo.temperature));
            //        };
                    break;

**Comment by stofakiller** [comment]
Just remove if(config.includethermostat)

**Comment by bitmerchandise** [comment]
Still doesn't work even after deletion of persist and starting over with homekit.

I see the device here

 { "name": "Honeywell", "altid": "11", "id": 67, "category": 5, "subcategory": 1, "room": 10, "parent": 1, "fanmode": "Auto", "mode": "HeatOn"

when i go to

http://IP:3480/data_request?id=lu_sdata

Category is also seen 

{ "name": "Thermostat", "id": 5 },

Any suggestions?

**Comment by tzonto** [comment]
you shouldn't remove the "if", just add "includethermostat: true" to your config file and it should pickup the thermostat. If it doesn't work run it in debug mode and post the output so we can see what is going on.

**Comment by bitmerchandise** [comment]
my error was "includethermostat": true and not what you sent me "includethermostat: true" plus I had an ignore for a scene that had same ID as thermostat, so I recreated the scene. thanks working now

**Comment by jacobleilei** [comment]
Thanks to @damianxd now I can use siri to work with vera.
Now I want to add more to control.
Like window covering and thermostat.
I tried @bitmerchandise 's way, add "includethermostat: true" to my config file.
My thermostat showed in homebridge initiating list, but not in apple app "Home" list.

**Comment by jacobleilei** [comment]
Thanks to @damianxd now I can use siri to work with vera.
Now I want to add more to control.
Like window covering and thermostat.
I tried @bitmerchandise 's way, add "includethermostat: true" to my config file.
My thermostat showed in homebridge initiating list, but not in apple app "Home" list.
How to proceed?
And how to run window covering nodes?

**Comment by jacobleilei** [comment]
@bitmerchandise After I reboot the bridge, it now works. I can control thermostat now.

**Comment by reallybman** [comment]
@bitmerchandise @jacobleilei can you advise on where to find this file that you are editing the thermostat IF statement?

**Comment by bitmerchandise** [comment]
mine is located in /usr/local/lib/node_modules/homebridge-vera
The actual files are in /usr/local/lib/node_modules/homebridge-vera/lib/types

Good luck

**Comment by bitmerchandise** [comment]
This is what worked for me though  "includethermostat: true"
I only attempted to edit the files once I saw someone else was successful by doing that.
If you already did that, then check if your thermostat ID is not excluded in your config.json or check that it doesn't have a duplicate ID as a scene... That has happened to me also. For some reason, scenes sometimes can have same ID as a device
