### ISSUE TITLE
forever homebridge

### ISSUE THREAD

**Issue by JiPi72** [damianxd/homebridge-vera#46]
Hi Damian,
I installed Homebridge and add-on in Ubuntu 16.04 in a VM in vSphere 6. I tried to launched Homebridge: sudo forever start / usr / bin / Homebridge
but the service is still falling!
Do you have a solution for that is still active?

**Comment by JiPi72** [comment]
Nobody can help me ?

**Comment by bitmerchandise** [comment]
you need to provide more information... Logs etc. I use pm2 to start my homebridge 

pm2 start homebridge

pm2 logs    --- will give you logging info

see docs

http://pm2.keymetrics.io/docs/usage/quick-start/

**Comment by damianxd** [comment]
At least for me the forever works, but you could try with the official homebridge tutorial on bootup (systemd)

https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi
