### ISSUE TITLE
iOS 10 or Sierra

### ISSUE THREAD

**Issue by erpeters33** [damianxd/homebridge-vera#47]
Homebridge starts fine and can be paired with iOS 10 Home app when Homebridge-vera platform is not in the config.json.  As soon as I add Vera to the config.json, iOS 10 Home throws error "Couldn't add Homebridge.  home couldn't connect to this accessory."  Any thoughts?

**Comment by bitmerchandise** [comment]
This happened to me when I had more than 100 devices. I don't know if that is your case but try ignoring some devices or delete scenes that you might not use anymore. 

Good luck

**Comment by erpeters3** [comment]
Thanks for the insight. I am WAY over 100 and doubt I can reasonably get below. I could troubleshoot if someone could tell me how to use the Ignore Rooms attribute. Then maybe we could put in an ask to troubleshoot that bug.

**Comment by bitmerchandise** [comment]
Ignore rooms is currently not working (I believe) but you can use ignoredevices check the readme on how to add the devices. If you check the homebridge logs you will see the devices being added and can then decide which ones to ignore

**Comment by erpeters3** [comment]
Using Atom as the editor, the line length for IgnoreDevices goes grey after perhaps 80. It appears at this length that the config file is non functional. Tried using two lines, both starting with IgnoreDevices. Failed. Can you use ranges like 210-214 or is only comma delimited allowed?
