### ISSUE TITLE
Dimmer Percentages

### ISSUE THREAD

**Issue by erpeters3** [damianxd/homebridge-vera#48]
When I set dinners to a percentage with a Scene, they very shortly jump up to 100%. Any ideas?

**Comment by drewcovi** [comment]
This is probably a dupe of #25

**Comment by pattont** [comment]
I'm having the same issue. Updated my Homebridge Vera Plugin and am running UI7. My dimmer is on a fan and when I set the fan to 50% in a scene it jumps straight to 100%, but the UI still shows 50%.
