### ISSUE TITLE
Ignore scenes ?

### ISSUE THREAD

**Issue by GreenTentacle** [damianxd/homebridge-vera#49]
I looked through all the documentation i could find, but I can't see if there's some way to disable using scenes in the newest version ?  Is there an "ignorescenes" directive I can put in the `config.json` ?  I tried literally using `includescene` to try to match the `includesensor`, but it didn't seem to work.

I have a ton of scenes on my Vera that I don't want to clutter up my homekit.

Thanks !

**Comment by GreenTentacle** [comment]
This is being used with homebridge, btw.

**Comment by bitmerchandise** [comment]
Scenes are treated as devices so just put the scene number in the ignoredevices

**Comment by GreenTentacle** [comment]
That almost works for me, but I have a device #5 as well as a scene #5 (for totally different things)

**Comment by bitmerchandise** [comment]
I had one of those, I just recreated the scene

**Comment by GreenTentacle** [comment]
That works as a workaround for now, thanks !!
