### ISSUE TITLE
Ok Dimmer Support!

### ISSUE THREAD

**Issue by DrJeff** [damianxd/homebridge-vera#5]
I have setup you awesome plugin @damianxd  and I get dimmers to work right out of the box! That is using the slider or telling Siri:
>"Turn on $ to 0%"

 For OFF or telling another % for ON.

This is working great, now for the ON and OFF command to work? 
What do I need to do to help? 
What log files or what to test?

Thanks!

**Comment by dustindclark** [comment]
I can confirm that this works with my (now-recalled) dimmer: http://www.vivint.com/remotec-recall

**Comment by DrJeff** [comment]
@richardbowman
Yes that change of line 32 was what I needed Thanks!

**Comment by damianxd** [comment]
No, just do that when you change between homebridge to the stand alone version or to VeraHomeKitBridge. Changes on a single device shouldn't have the need to clear anything

**Comment by DrJeff** [comment]
Thanks all set!
