### ISSUE TITLE
Scenes and devices seem to use the same Device number, prevents causes failure to add bridge to homekit

### ISSUE THREAD

**Issue by xeinth** [damianxd/homebridge-vera#53]
I have a lot of devices, and seemed to be over the element limit so I looked at ignoring some devices.  The symptom was you could see the bridge from homekit, but couldn't add it.  As I added devices to the ignore list, I noticed that many devices and scenes shared the same device.  Once I inadvertently removed the duplicates by removing all scenes, I could add the bridge thru homekit.

Not sure if this is the larger issue with supporting more devices as the probability for this occurring increases, but it would seem that scenes and devices should be offset in terms of device numbers to avoid conflicts.

an example of the startup log, for example device 51, 52 and others are duplicated:
Process Device 458: Mini Fridge
Ignore Device 52: Nook Light
Process Device 3: Outdoor Switch - Rope Lighting
Process Device 48: Pantry Light
Ignore Device 53: Patio Fans
Ignore Device 54: Patio Lights
Process Device 83: Side garage
Ignore Device 51: Stair Light
Process Device 488: Study Entry
Process Device 65: Study Fans
Process Device 147: Study Flood
Process Device 35: Study Lamp
Process Device 299: TV
Process Device 365: Upstairs hall
Process Device 462: Upstairs Mode
Process Device 296: Uverse
Process Device 38: Wine Flood
Process Device 144: Wine Undercabinet
Process Device 314: Xmas tree
Process Device 166: Alarm
Process Device 165: All Off
Process Device 56: All On
Process Device 73: Backyard Off
Process Device 65: Backyard On
Process Device 167: Bed Time
Ignore Device 123: Car Off
Ignore Device 122: Car On
Process Device 115: Christmas On
Process Device 116: Christmas off
Process Device 164: Clean On
Ignore Device 128: Do nothing
Ignore Device 54: Entry Night
Ignore Device 55: Entry Off
Ignore Device 70: Family Off
Ignore Device 66: Family On
Ignore Device 53: Front Yard Off
Ignore Device 52: Front Yard On
Ignore Device 81: Garage Halls Off
Ignore Device 80: Garage Halls On
Process Device 162: Good Day
Process Device 120: Good Evening
Process Device 163: Good Morning
Process Device 58: Good Night
Process Device 160: Goodbye
Ignore Device 62: Kitchen Day
Ignore Device 63: Kitchen Mood
Ignore Device 49: Kitchen Night
Ignore Device 51: Kitchen Off
Ignore Device 64: Master Bedtime
Ignore Device 6: Master Off
Ignore Device 4: Master On
Ignore Device 61: Outdoor Off
Ignore Device 59: Outdoor On
Ignore Device 127: RunHomeMode
Ignore Device 124: RunNightMode
Ignore Device 8: Study off
Ignore Device 142: Theater Entertain
Ignore Device 141: Theater Movie
Ignore Device 143: Theater Off
Ignore Device 168: Workflow 0-5
[11/8/2016, 2:11:24 AM] [Vera] Initializing platform accessory 'Back flood'...
[11/8/2016, 2:11:24 AM] [Vera] Initializing platform accessory 'Brian Lamp'...

**Comment by drewcovi** [comment]
@xeinth are you still dealing with this on master?

**Comment by xeinth** [comment]
I can validate, but it crippled the usage enough I wasn't actively working the issue. 

Original transmission from my mobile
