### ISSUE TITLE
Asking Siri to lock or unlock doors stopped working

### ISSUE THREAD

**Issue by reallybman** [damianxd/homebridge-vera#60]
Hi All - devices are adding fine and functioning fine when using physical buttons in the homekit app. I am able to use voice commands to control lights without a problem. I recently upgraded the Vera firmware to its latest release and I fear that may have caused voice commands for locks to stop working. I have a ticket in with Vera to see if I can downgrade to the previous firmware version to test if that is the issue. Anyone else having a problem with locks suddenly not functioning?

**Comment by bitmerchandise** [comment]
Confirmed! I have the same problem but if it is part of a scene the lock works

**Comment by drewcovi** [comment]
It may be more related to Siri. Can you confirm whether the lock / unlock works from within the Home app?

I'm on a beta channel of iOS and suffice to say sometimes Siri and HomeKit don't communicate well.

**Comment by reallybman** [comment]
@bitmerchandise Agreed - scenes and switches are working perfectly fine.

@drewcovi - Yes - the buttons work for everything in the app, Siri seems to be the problem. This morning my homebridge-liftmaster2 stopped working for my garage via Siri. Again, works fine within the Homekit app. Grr. Really liked the Siri features since I have the Apple Watch...

**Comment by reallybman** [comment]
@drewcovi - cancel the garage issue. It is working, I just have to make sure I say "Close the garage door". I was omitting the "the" which confused Siri. The locks, however, still not working.

**Comment by bitmerchandise** [comment]
i agree, seems it is siri and probably the latest "update" i don't normally say unlock door but i do recall a few weeks back that i tried it and had to send one of the kids to unlock the door :)

**Comment by reallybman** [comment]
Now Siri says "sorry, I can't do that for you" which makes me think Apple disabled the feature for security reasons. Bummer.

**Comment by bitmerchandise** [comment]
Wow a security feature that can be bypassed with a scene. Way to go apple! Just create some scenes like open bat cave or open bat hangar... have some fun with it :)

**Comment by drewcovi** [comment]
Again folks: pretty sure if you can lock and unlock the door from the Home app then it has nothing to do with security or homebridge. It's just a bug in iOS. We can take a closer look later.  But something tells me it does get hung up on the touchid check.

**Comment by Shad-Shad** [comment]
Hi, I'm having the same issue since i upgraded to iOS 10.2. Locking/unlocking works from the Home App without any issues, but when asking Siri to unlock the door, it does not work. I checked on the main Homebridge page and there is an issue open there (https://github.com/nfarina/homebridge/issues/1000) for this. Looks like Apple is now making Siri use Booolen instead of 0 and 1. The suggestion there is for the plugin developer to change the code to handle the Boolean. @drewcovi, can you please have a look. Thanks

**Comment by drewcovi** [comment]
@shad-shad not sure if this is the root of the cause. I'll take a look but I don't believe we're doing a strict === comparison. 1/true 0/false are fairly compatible in vanilla js. Perhaps we do need to translate it into a number though for the Vera API to be happy.

**Comment by Shad-Shad** [comment]
@drewcovi Thanks for the response. Please let me know if you would want me to test/validate any changes.
