### ISSUE TITLE
Hide Vera Scenes?

### ISSUE THREAD

**Issue by pattont** [damianxd/homebridge-vera#61]
I guess this is a feature request, but I'd love the option to hide Vera Scenes. I have a lot of scenes mainly for cheap zwave remotes (I.e. Fan high, fan medium, all downstairs lights off). It's quite cluttered in HomeKit and even though the scenes work I would just prefer a way to get rid of them and create HomeKit scenes for just a few things I want to access quickly with Siri.

**Comment by funstuff234** [comment]
I created a room in Homekit called "Ignore" and just moved them all over there.

**Comment by pattont** [comment]
haha :-)

**Comment by bitmerchandise** [comment]
Scenes have ID's. just put them in the ignoredevices within your config.json ...

**Comment by skinnedpt** [comment]
How to check scene and hue lights id?

**Comment by bitmerchandise** [comment]
after I updated to the latest version, my scenes starting showing up again and looked into the code, you can use 

`"ignorescenes": [sceneid,sceneid]`

to check scene id's, you can go to vera, click on scenes and there is a number beside the name in format 
[id: 220]

That is your scened ID/number

**Comment by bitmerchandise** [comment]
can someone please add ignorescenes to the readme...

thanks

**Comment by drewcovi** [comment]
Sure, but you can too 😄

Just click the edit button on the readme source view. Github creates a quick pull request.

**Comment by bitmerchandise** [comment]
done! Thank you for enlightening me. I always like to help out whenever I can...
Least I can do for all yours and Damian's hard work

**Comment by drewcovi** [comment]
@bitmerchandise did the pull request get made?

don't see it anywhere...

**Comment by bitmerchandise** [comment]
@drewcovi i thought i had done it before, was at work last time so I probably rushed it. should be there now. take care
