### ISSUE TITLE
Dimmer Delay Needed

### ISSUE THREAD

**Issue by pattont** [damianxd/homebridge-vera#67]
When dragging my finger to the percentage I want a fan to be at for instance it triggers the fan a ton on the way. Not sure if this if this is fixable with the current method of "hacking" devices into HomeKit, but some sort of delay until you finger is released needs to be put in. That's how the Vera app works with dimmers so perhaps in the plugin a delay can be added to keep it from pinging my fan 50 times on the way to 50%.

**Comment by djrobx** [comment]
Have you tried it with the latest code?

The latest update I committed fixes issues with overlapping Vera requests and makes the dimmers/fan controls work way more smoothly than they used to.    Now, if Homebridge is in the process of doing a level set and more requests come in, they are ignored until Vera finishes setting the level.    So there are much fewer intermediate requests going to Vera than before. 

If a delay is added I'd like it to be configurable.   I vastly prefer responsive controls.

**Comment by pattont** [comment]
I did an sudo npm -g update homebridge-vera and it successfully installed 0.5.4 and after starting homebridge, everything looks in order with my devices but now my iPhone shows "updating" on every devices and nothing appears to be working.
