### ISSUE TITLE
No response homebridge v 0.5.4

### ISSUE THREAD

**Issue by bitmerchandise** [damianxd/homebridge-vera#71]
i updated to v 0.5.4 and homebridge is not responding at all
errors logged are

0|homebrid | TypeError: functions.getVariable is not a function
0|homebrid |     at Object.Lock.getLockStatus (/usr/local/lib/node_modules/homebridge-vera/lib/types/lock.js:48:45)
0|homebrid |     at null._repeat (/usr/local/lib/node_modules/homebridge-vera/lib/types/lock.js:137:31)
0|homebrid |     at wrapper [as _onTimeout] (timers.js:275:11)
0|homebrid |     at Timer.listOnTimeout (timers.js:92:15)

**Comment by drewcovi** [comment]
Is that master? getVariable is in functions.js on master...

**Comment by djrobx** [comment]
There seems to be some problem with the package.   I tried npm update and got the same issue.   If you copy functions.js from master (just click the "clone or download" button here on Github), and overwrite the one the package manager wrote, it works fine.

On my system it ends up in /usr/local/lib/node_modules/homebridge-vera/lib

**Comment by bitmerchandise** [comment]
Thanks! Will try it out later, just got up :)
Happy new year to all

**Comment by bitmerchandise** [comment]
That worked. Thanks 
The one installed by npm is smaller in size
