### ISSUE TITLE
0.5.4 Update Now Devices Show "No Response"

### ISSUE THREAD

**Issue by pattont** [damianxd/homebridge-vera#72]
I did an `sudo npm -g update homebridge-vera `and it successfully installed 0.5.4 and after starting homebridge, everything looks in order with my devices but now my iPhone shows "updating" on every device and eventually times out to a "no response". I checked if there were homebridge updates as well and there weren't. 

Again, everything from the console looks to be started and showing my PIN as it always has. Since this update I seem to be hosed.

**Comment by bitmerchandise** [comment]
See the following closed issue No response homebridge v 0.5.4 #71

**Comment by pattont** [comment]
Perfect -- fixed it.. Should have searched closed.
