### ISSUE TITLE
Suggestion: Scenes as momentary switches

### ISSUE THREAD

**Issue by wharzhee** [damianxd/homebridge-vera#77]
Since vera scene is a set of actions that is carried out when a specific trigger occurs (there's no "on" or "off" mode), is there a way to set scenes as momentary switches?

**Comment by damianxd** [comment]
Vera does keep track if a scene is currently turned on, but you are right... it doesn't look like it is working properly. I will make the switches turn off automatically after a few seconds.

**Comment by funstuff234** [comment]
The auto-turn off code in the latest release doesn't seem to do anything for me. The scene switch should automatically revert to off after a few seconds, correct?

**Comment by damianxd** [comment]
yeah, it didn't work. The problem is that I don't know how to send a call to HAP to refresh the current value. It can be done on locks, but I haven't been able to find one for lights and switches

**Comment by drewcovi** [comment]
Scenes are now presented as switches that automatically reset in HomeKit. There are momentary switch services available, but they are read-only, meaning they can only trigger Automations in HomeKit, not the other way around.
