### ISSUE TITLE
ignore rooms not working

### ISSUE THREAD

**Issue by Juppers** [damianxd/homebridge-vera#88]
I have 2 rooms in the ignore list, but all scenes and devices in those rooms are still showing up. What's worse is the scenes show up in every room, not just the room it is associated with. Is there another way to hide devices and scenes when running standalone?

**Comment by cmonteiro128** [comment]
try ignoreDevices instead (using device number)

**Comment by Juppers** [comment]
Does that work for scenes as well? Scenes are what I really need to exclude.

**Comment by cmonteiro128** [comment]
I believe it does, but not 100% on that. I'd go ahead and give it a try (I believe scene # == device in Vera).

**Comment by bitmerchandise** [comment]
It works and I can confirm 100%. One gotcha is that, I have come across devices and scenes with same ID number so make sure they are unique...
I have recreated scenes when this has happened

**Comment by cmonteiro128** [comment]
Thanks for testing! And yea I think I remember that happening to me as well.

**Comment by drewcovi** [comment]
Sidenote: ignoredevices is not camelCase last I checked. Verify in functions.js

**Comment by cmonteiro128** [comment]
Yea you're right, its just "ignoredevices"

**Comment by Juppers** [comment]
That seems to work. I have 2 devices I can turn off but not on, still digging into those. One is a Harmony activity, the other is a standard on/off switch, but the ID is triple digit, 116.
