### ISSUE TITLE
Thermostat and switch issue

### ISSUE THREAD

**Issue by stofakiller** [damianxd/homebridge-vera#96]
Hi,

I havent upgraded anything since december, so now i have everything updated
Node 7.4.0
Nodejs 6.9.5
Homebridge 0.4.16
Homebridge-vera 0.5.9

And i have other things connect to homebridge, but i only have problems with my updated veraEdge (latest firmware)
I have Danfoss thermostats and at startup i get the correct reading of the temp, but something is wrong:
 VeraLink Getting target temp value for Stue1 +12ms
  VeraLink Making setpoint request for device Stue1 +1ms
  VeraLink [Before Conversion] Current Temperature for Thermostat #Stue1 is 22 +3ms
  VeraLink Current Temperature for Thermostat #Stue1 is 22 +1ms
  VeraLink Temperature display unit for Stue1 is 0 +6ms
  VeraLink Getting current heating/cooling state for Stue1 +11ms
  VeraLink Making hvacstate request for device Stue1 +2ms
  VeraLink HVAC State returned as:  undefined +1ms
  VeraLink Getting target heating/cooling value for Stue1 +2ms
  VeraLink Getting current temp. value for Stue1 +3ms
  VeraLink Making temperature request for device Stue1 +1ms
  VeraLink [Before Conversion] Current Temperature for Thermostat #Stue1 is NaN +1ms
  VeraLink Current Temperature for Thermostat #Stue1 is NaN +3ms

And i also have an Flex-Control Z-wave switch that i cant control with homebrige-vera any more:
In my vera it has ID:22 and uses D_BinaryLight1.xml and D_BinaryLight1.json

At startup:
 VeraLink Making request for device Tændsluk1 +1ms
  VeraLink LEVEL IS  0 +0ms

And when i switch it on and off (but nothing happens at my Vera
VeraLink Making request for device Tændsluk1 +2s
  VeraLink Requesting: http://192.168.1.19:3480/data_request?id=lu_action&output_format=json +309ms
  VeraLink Light Power set +55ms
  VeraLink { 'u:SetTargetResponse': { JobID: '288' } } +1ms
  VeraLink Caching status... +692ms
  VeraLink Caching status... +3s
  VeraLink Caching status... +3s
  VeraLink Making request for device Tændsluk1 +649ms
  VeraLink Requesting: http://192.168.1.19:3480/data_request?id=lu_action&output_format=json +302ms
  VeraLink Light Power set +33ms
  VeraLink { 'u:SetTargetResponse': { JobID: '289' } } +1ms

Hope anyone can help :-)

Regards Jan

**Comment by drewcovi** [comment]
Can you install direct from master and report back? I can publish to NPM as soon as I get word back from @damianxd to get the latest out.

**Comment by stofakiller** [comment]
Hi,

I did a npm install homebridge-vera, issent that the master?

**Comment by drewcovi** [comment]
You'll want to install using the GitHub URL not the package name. When I can publish the latest go back to the name.

**Comment by stofakiller** [comment]
Super, that worked for the switch, but no change for the thermostat's

**Comment by drewcovi** [comment]
@stofakiller can you provide the thermostat portion of the json response for:

http://[yourVeraIP]:3480/data_request?id=sdata

**Comment by stofakiller** [comment]
Hi,

I have it here from an earlier post...

https://github.com/damianxd/homebridge-vera/issues/45#issuecomment-255330242

**Comment by drewcovi** [comment]
@stofakiller could you pull from the URL provided instead? 

That's not the same request and not Json

**Comment by stofakiller** [comment]
Ok, sure:

{ "full": 1, "version": "*1.7.2406*", "model": "Sercomm NA301", "zwave_heal": 1, "temperature": "C", "skin": "mios", "serial_number": "45108814", "fwd1": "vera-eu-oem-relay11.mios.com", "fwd2": "vera-eu-oem-relay12.mios.com", "mode": 1, "sections": [ { "name": "My Home", "id": 1 } ], "rooms": [ { "name": "Danfoss", "id": 1, "section": 1 }, { "name": "Kontakter", "id": 4, "section": 1 }, { "name": "Stue", "id": 2, "section": 1 }, { "name": "_Legestue", "id": 3, "section": 1 } ], "scenes": [ { "name": "Affugter Sluk", "id": 25, "room": 0, "state": -1, "comment": "", "active": 0 }, { "name": "Affugter tænd", "id": 24, "room": 0, "active": 1, "state": -1, "comment": "" }, { "name": "Køleboks tænd", "id": 1, "room": 0, "active": 1 }, { "active": 1, "name": "Post", "id": 16, "room": 0 }, { "active": 1, "name": "ServerShutdown", "id": 3, "room": 0 }, { "active": 0, "name": "Varme Ferie hjem", "id": 10, "room": 0 }, { "active": 1, "name": "Varme Weekend", "id": 4, "room": 0 }, { "active": 1, "name": "Varme ferie", "id": 9, "room": 0 }, { "active": 1, "name": "Varme hverdag", "id": 5, "room": 0 }, { "active": 1, "name": "_BatteryCheck", "id": 17, "room": 0 } ], "devices": [ { "name": "(*)Evas iPhone", "altid": "", "id": 87, "category": 0, "subcategory": -1, "room": 3, "parent": 0, "muted": "0", "commFailure": "0", "present": "0", "location": "Haardalen, 8680 Ry, Denmark", "curlat": "56.078725028835", "curlong": "9.7834842838438", "distance": "45.624" }, { "name": "(*)Majas iPhone", "altid": "", "id": 88, "category": 0, "subcategory": -1, "room": 3, "parent": 0, "muted": "0", "commFailure": "0", "present": "1", "curlat": "56.299973242037", "curlong": "10.144742801795", "distance": "0.338", "location": "Ågade 1, 8380 Trige, Denmark" }, { "name": "Badværelse", "altid": "28", "id": 102, "category": 5, "subcategory": 2, "room": 1, "parent": 1, "mode": "HeatOn", "setpoint": "22.00", "heat": "22.00", "cool": "22.00", "status": "1", "commands": "heater_setpoint", "commFailure": "0", "batterylevel": "48", "state": -1, "comment": "" }, { "name": "Battery Monitor", "altid": "", "id": 49, "category": 0, "subcategory": -1, "room": 3, "parent": 0, "status": "3" }, { "name": "Danfoss Repo", "altid": "45", "id": 141, "category": 5, "subcategory": 2, "room": 1, "parent": 1, "mode": "HeatOn", "setpoint": "20.00", "heat": "20.00", "cool": "20.00", "status": "1", "commands": "heater_setpoint", "batterylevel": "47", "commFailure": "1" }, { "name": "Day or Night", "altid": "", "id": 23, "category": 0, "subcategory": -1, "room": 3, "parent": 0, "status": "1" }, { "name": "Dimmable Light", "altid": "49", "id": 142, "category": 2, "subcategory": 0, "room": 0, "parent": 1, "status": "1", "level": "100", "commFailure": "1", "state": -1, "comment": "" }, { "name": "Embedded Humidity S", "altid": "e2", "id": 125, "category": 16, "subcategory": 0, "room": 3, "parent": 123, "humidity": "20", "temperature": "21.6" }, { "name": "Embedded Temperatur", "altid": "e1", "id": 124, "category": 17, "subcategory": 0, "room": 3, "parent": 123, "temperature": "21.7" }, { "name": "Fibaro TS2", "altid": "15", "id": 31, "category": 3, "subcategory": 1, "room": 4, "parent": 1, "status": "1", "watts": "", "kwh": "185.1200", "commFailure": "1", "tripped": "1", "armedtripped": "1", "lasttrip": "1449505544", "armed": "0", "state": -1, "comment": "" }, { "name": "High Temperature", "altid": "Weather-Forecast-HighTemperature", "id": 76, "category": 17, "subcategory": 0, "room": 3, "parent": 73, "temperature": "6" }, { "name": "Home Energy Monitor", "altid": "21", "id": 69, "category": 21, "subcategory": 0, "room": 3, "parent": 1, "kwh": "2537.5800", "watts": "389", "batterylevel": "100", "commFailure": "1", "status": "1", "setpoint": "10", "heat": "10", "cool": "10", "state": -1, "comment": "" }, { "name": "Humidity", "altid": "Weather-Current-Humidity", "id": 126, "category": 16, "subcategory": 0, "room": 3, "parent": 73, "humidity": "89" }, { "name": "Istappelys", "altid": "51", "id": 144, "category": 3, "subcategory": 1, "room": 0, "parent": 1, "status": "1", "watts": "", "kwh": "0.7800", "commFailure": "1", "state": -1, "comment": "" }, { "name": "Low Temperature", "altid": "Weather-Forecast-LowTemperature", "id": 75, "category": 17, "subcategory": 0, "room": 3, "parent": 73, "temperature": "1" }, { "name": "Maja", "altid": "38", "id": 110, "category": 5, "subcategory": 2, "room": 1, "parent": 1, "mode": "HeatOn", "setpoint": "21.00", "heat": "21.00", "cool": "21.00", "status": "1", "commands": "heater_setpoint", "commFailure": "0", "batterylevel": "89", "state": -1, "comment": "" }, { "name": "PIR", "altid": "17", "id": 47, "category": 4, "subcategory": 3, "room": 3, "parent": 1, "lasttrip": "1455633849", "armed": "1", "armedtripped": "0", "batterylevel": "90", "commFailure": "1" }, { "name": "Postkasse", "altid": "44", "id": 128, "category": 4, "subcategory": 1, "room": 4, "parent": 1, "armed": "1", "lasttrip": "1486217937", "armedtripped": "1", "tripped": "1", "batterylevel": "40", "commFailure": "0", "state": -1, "comment": "" }, { "name": "Power Arithmetic", "altid": "", "id": 91, "category": 0, "subcategory": -1, "room": 3, "parent": 0, "watts": "50.9", "commFailure": "0" }, { "name": "Push Notification", "altid": "", "id": 26, "category": 1, "subcategory": 0, "room": 3, "parent": 0, "status": "0", "armed": "1", "armedtripped": "0" }, { "name": "Sofie", "altid": "40", "id": 112, "category": 5, "subcategory": 2, "room": 1, "parent": 1, "mode": "HeatOn", "setpoint": "21.00", "heat": "21.00", "cool": "21.00", "status": "1", "commands": "heater_setpoint", "commFailure": "0", "batterylevel": "81", "state": -1, "comment": "" }, { "name": "Soveværelse", "altid": "39", "id": 111, "category": 5, "subcategory": 2, "room": 1, "parent": 1, "mode": "HeatOn", "setpoint": "21.00", "heat": "21.00", "cool": "21.00", "status": "1", "commands": "heater_setpoint", "batterylevel": "58", "state": -1, "comment": "" }, { "name": "Stue1", "altid": "36", "id": 108, "category": 5, "subcategory": 2, "room": 1, "parent": 1, "mode": "HeatOn", "setpoint": "22.00", "heat": "22.00", "cool": "22.00", "status": "1", "commands": "heater_setpoint", "batterylevel": "67", "state": -1, "comment": "" }, { "name": "Stue2", "altid": "33", "id": 105, "category": 5, "subcategory": 2, "room": 1, "parent": 1, "mode": "HeatOn", "setpoint": "22.00", "heat": "22.00", "cool": "22.00", "status": "1", "commands": "heater_setpoint", "batterylevel": "68", "state": -1, "comment": "" }, { "name": "Temp Humidity Senso", "altid": "42", "id": 123, "category": 11, "subcategory": 0, "room": 3, "parent": 1, "batterylevel": "20", "humidity": "20", "temperature": "21.6", "state": -1, "comment": "" }, { "name": "Temperature", "altid": "Weather-Current-Temperature", "id": 74, "category": 17, "subcategory": 0, "room": 3, "parent": 73, "temperature": "5.9" }, { "name": "Tændsluk1", "altid": "13", "id": 22, "category": 3, "subcategory": 0, "room": 4, "parent": 1, "commFailure": "0", "setpoint": "21", "heat": "21", "cool": "21", "status": "1", "state": -1, "comment": "" }, { "name": "Wake-on-LAN", "altid": "", "id": 28, "category": 0, "subcategory": -1, "room": 3, "parent": 0 }, { "name": "WOL Plus Ping", "altid": "", "id": 29, "category": 3, "subcategory": -1, "room": 3, "parent": 0, "ip": "192.168.1.105", "status": "0" }, { "name": "World Weather", "altid": "", "id": 73, "category": 0, "subcategory": -1, "room": 3, "parent": 0, "providerkey": "54daf8b8af9b1506", "providername": "WUI (Weather Underground)", "providerurl": "http:\/\/www.wunderground.com", "heat": "", "f": "3", "a": "1", "a1.type": "WIN", "a1.desc": "<![CDATA[Disruption due to snow and ice from 5PM CET THU until 11:59PM CET THU]]>", "a1.start": "NA", "a1.end": "NA", "a1.msg": "<![CDATA[Disruption due to snow and ice from 5PM CET THU until 11:59PM CET THU]]>", "a1.phenom": "NA", "a1.signif": "NA", "a1.attrib": "<![CDATA[Information provided by , <a href='http:\/\/meteoalarm.eu\/'>EUMETNET - MeteoAlarm<\/a> Note: Time delays between this website and <a href='http:\/\/meteoalarm.eu\/'>Meteoalarm.eu<\/a> are possible. For the most up-to-date information about alert levels as published by the participating National Meteoroological Services, please visit <a href='http:\/\/meteoalarm.eu\/'>Meteoalarm<\/a>. For terms of use of this information, and copyright information, see <a href='http:\/\/meteoalarm.eu\/'>Meteoalarm<\/a> Terms of Use.\"]]>", "humidity": "74", "f1.condition": "Chance of Rain", "f1.conditiongroup": "chancerain", "f3.windspeed": "32", "f1.windspeed": "32", "f1.hightemp": "7", "f1.lowtemp": "3", "f1.winddirection": "E", "f2.winddirection": "ESE", "f3.condition": "Snow Showers", "f3.conditiongroup": "snow", "f3.winddirection": "ENE", "f0.lowtemp": "1", "f0.winddirection": "WSW", "f3.lowtemp": "-2", "f2.windspeed": "40", "f2.hightemp": "6", "f1.winddegrees": "100", "f2.lowtemp": "1", "f2.condition": "Chance of Rain", "f2.conditiongroup": "chancerain", "f0.snownight": "0", "f3.winddegrees": "67", "f2.winddegrees": "119", "condition": "Overcast", "conditiongroup": "cloudy", "windgust": "15.8", "dew": "4", "f0.qpfnight": "1", "f3.hightemp": "3", "f0.snowday": "1.3", "f0.hightemp": "6", "f0.windspeed": "16", "f0.condition": "Chance of Rain", "f0.conditiongroup": "chancerain", "f0.winddegrees": "242", "f0.pop": "50", "f0.qpfday": "0", "windcondition": "From the South at 14.0 KPH Gusting to 15.8 KPH", "winddirection": "South", "winddegrees": "189", "windspeed": "14", "pressure": "1003", "pressuret": "-", "windchill": "3", "feels": "3", "solar": "17", "uv": "0" } ], "categories": [ { "name": "Interface", "id": 1 }, { "name": "Dimmable Switch", "id": 2 }, { "name": "On\/Off Switch", "id": 3 }, { "name": "Sensor", "id": 4 }, { "name": "Thermostat", "id": 5 }, { "name": "Generic IO", "id": 11 }, { "name": "Humidity Sensor", "id": 16 }, { "name": "Temperature Sensor", "id": 17 }, { "name": "Power meter", "id": 21 } ], "ir": 0, "irtx": "", "loadtime": 1488322826, "dataversion": 322885596, "state": -1, "comment": "" }

**Comment by drewcovi** [comment]
@stofakiller does it cause the thermostat to not show up or is it just showing without a temperature?

**Comment by drewcovi** [comment]
@stofakiller The Danfoss units don't show current temperature apparently, either within Vera or on the unit... just the target setpoint. So this isn't likely something that we can easily resolve...

http://forum.micasaverde.com/index.php?topic=12245.0

**Comment by stofakiller** [comment]
That tread is 4 1/2 years old... It worked last december...

**Comment by drewcovi** [comment]
Based on the json you've provided there's no key for that device that shows current temperature.

**Comment by drewcovi** [comment]
Only setpoin, heat and cool

**Comment by drewcovi** [comment]
This is what we have to work with from your system:

``{ "name": "Stue1", "altid": "36", "id": 108, "category": 5, "subcategory": 2, "room": 1, "parent": 1, "mode": "HeatOn", "setpoint": "22.00", "heat": "22.00", "cool": "22.00", "status": "1", "commands": "heater_setpoint", "batterylevel": "67", "state": -1, "comment": "" },``

**Comment by drewcovi** [comment]
@stofakiller does the Vera UI show current temperature? Worst case scenario I guess we could fall back to showing the setpoint, but most thermostats have both a setpoint and current temperature which HomeKit requires. When they are the same the icon changes from blue/orange to green.

**Comment by stofakiller** [comment]
I had to reinstall the hole thing, i remeber now, i changed the code in the vera xml. So i will do that or in homebridge-vera, when i got time, so just close this one...
